// Canonical data contract for the Education App "Inspector" runs.
//
// The frontend (chapter components and inspector visualizations under
// demo/learn/) imports these types. The backend (Rust NAPI in crates/mlx-core)
// must serialize its inspector payloads into shapes that match these types
// after NAPI / SAB transport.
//
// Until the backend hook lands, chapter components may construct mock
// AttentionRun values for development. The mock shape must validate against
// these types so swap-in is mechanical.

export type TokenInfo = {
  /** Token id from the Qwen3 tokenizer. */
  id: number;
  /** Decoded text for this token. May contain leading whitespace or special
   *  markers (e.g. "Ġthe", "<|im_start|>"). The frontend renders this verbatim. */
  text: string;
};

export type AttentionLayerKind = 'full' | 'linear';

export type AttentionLayer = {
  /** 0-based index into the model's full layer stack (not the index among
   *  full-attention layers only). */
  layerIndex: number;
  /** Qwen3.5 is hybrid: only 'full' layers have classic softmax attention
   *  scores. 'linear' layers (GatedDeltaNet) appear in the layer list for
   *  context but their `scores` field is empty. */
  kind: AttentionLayerKind;
  /** Number of query heads. */
  numHeads: number;
  /** Number of KV heads (GQA: numKvHeads <= numHeads, evenly divides numHeads). */
  numKvHeads: number;
  /** Softmaxed attention scores. Length === numHeads * seqLen * seqLen.
   *  Layout: [head_index][query_token_index][key_token_index], row-major.
   *  For 'linear' layers this is a zero-length Float32Array. */
  scores: Float32Array;
};

export type ModelMeta = {
  /** Human-readable model name (e.g. "Qwen3.5-0.8B"). */
  name: string;
  /** Total number of layers in the model. */
  numLayers: number;
  /** Indices (into the full 0..numLayers-1 range) of layers that use full
   *  attention. The inspector returns scores only for these. */
  fullAttentionLayerIndices: number[];
};

export type AttentionRun = {
  /** The prompt the user typed. */
  prompt: string;
  /** Prompt tokens after tokenization. Length === seqLen. */
  tokens: TokenInfo[];
  /** The first generated token. Kept for back-compat with callers that
   *  only render "the next token". For multi-token inspector runs prefer
   *  `generatedTokens` which holds the full decode sequence. */
  generatedToken: TokenInfo;
  /** All tokens generated by the inspector run, in order. Length equals
   *  the effective `maxNewTokens` (may be shorter if EOS was hit). The
   *  first element matches `generatedToken`. The forward-pass diagram
   *  joins these to render the model's full reply rather than a lonely
   *  scaffold token. Optional for backward compatibility with cached
   *  inspector runs that predate this field. */
  generatedTokens?: TokenInfo[];
  /** One entry per layer captured. Order matches `modelMeta.fullAttentionLayerIndices`. */
  attention: AttentionLayer[];
  /** Model identification + which layers carry attention scores. */
  modelMeta: ModelMeta;
  /** Per-step top-K logits, in generation order. Populated iff the
   *  inspector request set `logits: { topK }`. Each entry's `tokenId` is the
   *  token actually sampled at that step; under the inspector's greedy
   *  sampler it usually equals `topKIds[0]`, but exact-tie logits can break
   *  the equality due to unstable top-K partitioning. */
  logits?: LogitsStep[];
  /** Per-layer hidden-state summary statistics, in generation order.
   *  Populated iff the inspector request set `hiddenStates`. */
  hiddenStates?: HiddenStateStep[];
};

/** Canonical capture-point names in forward-pass order. Mirrors the Rust
 *  `HIDDEN_STATE_POINTS` constant in `crates/mlx-core/src/inspector.rs`. */
export const HIDDEN_STATE_POINTS = [
  'pre_attn_input',
  'post_attn_norm',
  'attn_output',
  'post_attn_residual',
  'post_mlp_norm',
  'mlp_output',
  'post_mlp_residual',
] as const;

export type HiddenStatePointName = (typeof HIDDEN_STATE_POINTS)[number];

/** Summary statistics for a single decoder-layer capture point.
 *  `std` is the population standard deviation (divides by `count`, not
 *  `count - 1`). All floats are computed in f32 on the Rust side and widened
 *  to f64 for NAPI transport. */
export type HiddenStatePointStats = {
  /** Capture-point name. Typically narrowed to `HiddenStatePointName`, but
   *  kept as a plain string so unknown points coming from the backend don't
   *  break the type. */
  point: string;
  mean: number;
  std: number;
  absMax: number;
  l2Norm: number;
  /** Total number of float elements considered for this capture (flattened
   *  across seq and hidden_dim). */
  count: number;
};

export type HiddenStateLayer = {
  /** 0-based index into the model's full layer stack. */
  layerIdx: number;
  /** Stats per capture point, in forward-pass order. May be a subset of the
   *  seven canonical names if the request filtered points. */
  stats: HiddenStatePointStats[];
};

export type HiddenStateStep = {
  /** 0-based generation step (0 == prefill, 1+ == decode). */
  step: number;
  /** Per-layer captures for this step, in forward-pass order. */
  layers: HiddenStateLayer[];
};

/** Per-step top-K logits capture. Lengths of `topKIds`, `topKLogits`, and
 *  `topKTexts` are all equal to `min(requested topK, vocab)`. Logits are
 *  raw pre-softmax values — the consumer applies temperature / softmax. */
export type LogitsStep = {
  /** 0-based generation step index. */
  step: number;
  /** Token id sampled at this step. */
  tokenId: number;
  /** Top-K token ids in descending logit order. */
  topKIds: number[];
  /** Raw logits matching `topKIds`, same order. NOT softmax probabilities. */
  topKLogits: Float32Array;
  /** Decoded text for each id in `topKIds`. */
  topKTexts: string[];
};

// -----------------------------------------------------------------------------
// Worker-bridge protocol (extends the existing mlx-worker.ts request/response).
// -----------------------------------------------------------------------------

export type InspectorRequest = {
  type: 'runForInspector';
  /** Caller-supplied correlation id. The worker echoes this in the response. */
  id: string;
  prompt: string;
  /** Capture attention scores. Default: false. */
  attention?: boolean;
  /** Restrict to specific full-attention layer indices. Default: all. */
  attentionLayers?: number[];
  /** Capture per-step top-K logits. Default: not captured. */
  logits?: { topK: number };
  /** Capture per-layer hidden-state summary stats at the seven canonical
   *  points around attention / MLP / residuals. Default: not captured.
   *  Stats only — no full activation arrays. */
  hiddenStates?: {
    /** Restrict to specific layer indices. Default: every layer. */
    layers?: number[];
    /** Restrict to a subset of the seven capture-point names. Default: all. */
    points?: string[];
  };
  /** How many new tokens to generate before returning. Default: 1. */
  maxNewTokens?: number;
  /** Wrap the prompt in the model's Jinja2 chat template before tokenizing.
   *  Default: false (feeds raw text — useful for the Tokenization /
   *  Embeddings chapters that show literal BPE). When true, the prompt is
   *  wrapped as a single-turn user message and the assistant generation
   *  prompt is appended, so the chat-tuned model runs in its natural
   *  distribution and the predicted next token reflects what a chat reply
   *  would actually start with. */
  applyChatTemplate?: boolean;
};

export type InspectorResult =
  | { type: 'inspectorResult'; id: string; result: AttentionRun }
  | { type: 'inspectorError'; id: string; error: string };

// -----------------------------------------------------------------------------
// Protocol string constants
// -----------------------------------------------------------------------------
//
// The worker (`mlx-worker.ts`) and the main-thread bridge
// (`demo/lib/inspector-client.ts`) both need to write/read these `type` fields
// on `postMessage` payloads. Exporting them here keeps the single source of
// truth in this file so the two ends can't drift on a typo. The TypeScript
// literal unions above (`type: 'runForInspector'` etc.) are intentionally kept
// as plain string literals for readability; the constants are the *runtime*
// values both sides use.

export const INSPECTOR_REQUEST_TYPE = 'runForInspector' as const;
export const INSPECTOR_RESULT_TYPE = 'inspectorResult' as const;
export const INSPECTOR_ERROR_TYPE = 'inspectorError' as const;

// -----------------------------------------------------------------------------
// Tokenize worker bridge (chapter 1 — Tokenization).
// -----------------------------------------------------------------------------
//
// The Tokenization chapter shows the live Qwen3 tokenizer slicing arbitrary
// strings into BPE sub-words. It needs only the token list (no attention
// scores, no generation), so we expose a thin worker message that returns a
// `TokenInfo[]`. The worker's implementation currently reuses the loaded
// `model.runForInspector` path with `attention: false, maxNewTokens: 1` to
// reach the tokenizer — the only access point exposed to JS without a Rust
// change — and discards the generated token. If we later add a tokenizer-only
// NAPI method the worker handler can switch over transparently.

export type TokenizeRequest = {
  type: 'tokenize';
  /** Caller-supplied correlation id. The worker echoes this in the response. */
  id: string;
  /** Raw string to tokenize. The tokenizer runs without the chat template — this
   *  is a "what does the model see for this exact string?" hook. */
  prompt: string;
};

export type TokenizeResult =
  | { type: 'tokenizeResult'; id: string; tokens: TokenInfo[] }
  | { type: 'tokenizeError'; id: string; error: string };

export const TOKENIZE_REQUEST_TYPE = 'tokenize' as const;
export const TOKENIZE_RESULT_TYPE = 'tokenizeResult' as const;
export const TOKENIZE_ERROR_TYPE = 'tokenizeError' as const;

// -----------------------------------------------------------------------------
// Embed worker bridge (chapter 2 — Embeddings).
// -----------------------------------------------------------------------------
//
// The Embeddings chapter projects the model's embedding matrix to 2D with PCA.
// It tokenizes a curated word list (via the existing `tokenize` message) and
// then needs the per-token embedding vector — `[N, hidden_dim]` floats. The
// worker handler calls the NAPI method `model.embedTokens(tokenIds)`, which
// runs `weight.take(token_ids, axis=0)` on the model thread and returns a
// flat row-major Float32Array. The buffer is transferred for zero-copy
// postMessage.

export type EmbedRequest = {
  type: 'embed';
  /** Caller-supplied correlation id. The worker echoes this in the response. */
  id: string;
  /** Token ids to look up. Each must be in `[0, vocab)`; out-of-range values
   *  surface as an `embedError` from the backend. */
  tokenIds: number[];
};

export type EmbedResult =
  | {
      type: 'embedResult';
      id: string;
      /** Flat row-major `[tokenIds.length, hiddenDim]` embeddings. */
      embeddings: Float32Array;
      hiddenDim: number;
    }
  | { type: 'embedError'; id: string; error: string };

export const EMBED_REQUEST_TYPE = 'embed' as const;
export const EMBED_RESULT_TYPE = 'embedResult' as const;
export const EMBED_ERROR_TYPE = 'embedError' as const;

// -----------------------------------------------------------------------------
// Notes for the backend implementer (crates/mlx-core, Rust).
// -----------------------------------------------------------------------------
//
// The Rust side should expose a NAPI method on the model class (or a new
// dedicated handle) with this signature:
//
//   #[napi]
//   pub fn run_for_inspector(
//     &self,
//     prompt: String,
//     opts: InspectorRunOptions,
//   ) -> napi::Result<AttentionRunNapi>;
//
// Where:
//
//   #[napi(object)]
//   pub struct InspectorRunOptions {
//     pub attention: Option<bool>,
//     pub attention_layers: Option<Vec<i32>>,
//     pub max_new_tokens: Option<i32>,
//   }
//
//   #[napi(object)]
//   pub struct AttentionRunNapi {
//     pub prompt: String,
//     pub tokens: Vec<TokenInfoNapi>,
//     pub generated_token: TokenInfoNapi,
//     pub attention: Vec<AttentionLayerNapi>,
//     pub model_meta: ModelMetaNapi,
//   }
//
//   #[napi(object)]
//   pub struct AttentionLayerNapi {
//     pub layer_index: i32,
//     pub kind: String, // "full" | "linear"
//     pub num_heads: i32,
//     pub num_kv_heads: i32,
//     pub scores: napi::bindgen_prelude::Float32Array,
//   }
//
// NAPI-RS converts snake_case Rust field names to camelCase JS field names
// automatically; the generated index.d.cts will match the TypeScript types
// above. Verify with `yarn build` and a `tsc --noEmit` smoke check.
//
// During the forward pass in qwen3_5/attention.rs, after computing
// `softmax(QK^T / sqrt(d_head))` and BEFORE the matmul with V, if the
// inspector toggle is on, copy the score tensor (shape: [num_heads, seq_q, seq_k])
// out of GPU memory into a CPU-side Vec<f32>. This is the layout consumed
// above (row-major, head-major).
//
// Performance: this hook is off by default. With it on, expect ~1.5-2x decode
// slowdown depending on captured layer count. Document this in the lesson copy.
