approvedGitRepositories:
  - "**"

catalog:
  "@types/node": "npm:@types/node@24.12.2"
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
  vite-plus: 0.0.0-commit.8b23a00f98df4a9270ac87a4f80b2ce1b669040b
  vitest: 4.1.10

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
npmPreapprovedPackages:
  - vitest
  - '@vitest/*'
npmRegistryServer: https://registry-bridge.viteplus.dev/
