approvedGitRepositories:
  - "**"

catalog:
  "@types/node": "npm:@types/node@24.12.2"
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  vite-plus: 0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  vitest: 4.1.10

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
npmPreapprovedPackages:
  - vitest
  - '@vitest/*'
npmRegistryServer: https://registry-bridge.viteplus.dev/
