catalog:
  "@types/node": "npm:@types/node@24.12.2"
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vite-plus: latest
  vitest: "npm:@voidzero-dev/vite-plus-test@latest"

nodeLinker: node-modules

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

supportedArchitectures:
  cpu:
    - x64
    - arm64

yarnPath: .yarn/releases/yarn-4.13.0.cjs
