// router.ts — TanStack Router wiring.
//
// Phase 2.A: Router exists but is dormant — <RouterProvider /> is NOT mounted
// from app.tsx yet. The router is created here so the Vite plugin can generate
// routeTree.gen.ts at dev-server startup.
//
// Phase 2.C will mount the RouterProvider and retire the query-param SPA.

import { createRouter } from '@tanstack/react-router';

// This file is auto-generated by @tanstack/router-plugin at dev/build time.
// It is gitignored and must never be committed.
import { routeTree } from './routeTree.gen';

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  // TODO(phase-2.c): wire defaultErrorComponent and defaultNotFoundComponent
  // before <RouterProvider /> is mounted in app.tsx.
});

// Register the router for type safety throughout the app.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
