// WASM Exception Handling Runtime for wasi-sdk
//
// wasi-sdk's libc++abi is built with -fno-exceptions, so it lacks the core
// exception symbols (__cxa_allocate_exception, __cxa_throw, etc.). This file
// provides them when compiled with -fwasm-exceptions for the WASI target.
//
// The JS host must provide a WebAssembly.Tag({parameters:["i32"]}) as the
// env.__cpp_exception import. This tag is used by the WASM throw/catch
// instructions generated by clang.

#if defined(WEBGPU_BACKEND_WASI_IMPORT)

#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <typeinfo>

namespace __cxxabiv1 {

// Exception header — lives just before the thrown object in memory.
// Layout must match what clang expects for the Itanium C++ ABI.
struct __cxa_exception {
  std::type_info* exceptionType;
  void* exceptionDestructor; // actually ptr(*)(ptr), stored as opaque
  unsigned handlerCount;
  __cxa_exception* nextException;
};

static inline __cxa_exception* header_from_object(void* obj) {
  return static_cast<__cxa_exception*>(obj) - 1;
}

// Per-thread caught exception stack
thread_local __cxa_exception* __cxa_caught_exceptions = nullptr;

} // namespace __cxxabiv1

// Landing pad context read/written by compiler-generated code at catch sites.
// Layout (observed from clang codegen for wasm32):
//   offset 0: initial selector (compiler writes 0 before personality call)
//   offset 4: LSDA pointer (compiler writes, personality reads)
//   offset 8: result selector (personality writes, compiler reads)
struct __wasm_lpad_context_t {
  int32_t initial_selector;
  void* lsda;
  int32_t result_selector;
};

extern "C" thread_local __wasm_lpad_context_t __wasm_lpad_context;
thread_local __wasm_lpad_context_t __wasm_lpad_context = {};

extern "C" {

void* __cxa_allocate_exception(size_t thrown_size) {
  size_t total = sizeof(__cxxabiv1::__cxa_exception) + thrown_size;
  auto* raw = std::malloc(total);
  if (!raw)
    std::abort();
  std::memset(raw, 0, sizeof(__cxxabiv1::__cxa_exception));
  return static_cast<__cxxabiv1::__cxa_exception*>(raw) + 1;
}

void __cxa_free_exception(void* thrown_object) {
  if (thrown_object) {
    std::free(__cxxabiv1::header_from_object(thrown_object));
  }
}

void __cxa_throw(
    void* thrown_object,
    std::type_info* tinfo,
    void (*dest)(void*)) {
  auto* header = __cxxabiv1::header_from_object(thrown_object);
  header->exceptionType = tinfo;
  header->exceptionDestructor = reinterpret_cast<void*>(dest);
  // Emit the WASM throw instruction for tag index 0 (__cpp_exception)
  __builtin_wasm_throw(0, thrown_object);
  __builtin_unreachable();
}

void* __cxa_begin_catch(void* exception_object) {
  if (!exception_object)
    return nullptr;
  auto* header = __cxxabiv1::header_from_object(exception_object);
  header->handlerCount++;
  header->nextException = __cxxabiv1::__cxa_caught_exceptions;
  __cxxabiv1::__cxa_caught_exceptions = header;
  return exception_object;
}

void __cxa_end_catch() {
  auto* header = __cxxabiv1::__cxa_caught_exceptions;
  if (!header)
    return;

  header->handlerCount--;
  if (header->handlerCount == 0) {
    __cxxabiv1::__cxa_caught_exceptions = header->nextException;

    void* thrown_obj = header + 1;
    void* dtor_raw = header->exceptionDestructor;
    header->exceptionDestructor = nullptr;

    if (dtor_raw) {
      // C++ destructors in WASM have signature (ptr) -> (ptr) — they return
      // 'this'. Cast accordingly to avoid indirect call signature mismatch.
      using dtor_fn = void* (*)(void*);
      reinterpret_cast<dtor_fn>(dtor_raw)(thrown_obj);
    }
    std::free(header);
  }
}

void* __cxa_init_primary_exception(
    void* obj,
    std::type_info* tinfo,
    void (*dest)(void*)) {
  auto* header = __cxxabiv1::header_from_object(obj);
  header->exceptionType = tinfo;
  header->exceptionDestructor = reinterpret_cast<void*>(dest);
  return obj;
}

void __cxa_rethrow() {
  auto* header = __cxxabiv1::__cxa_caught_exceptions;
  if (!header)
    std::abort();
  void* obj = header + 1;
  __cxxabiv1::__cxa_caught_exceptions = header->nextException;
  header->handlerCount--;
  __builtin_wasm_throw(0, obj);
  __builtin_unreachable();
}

// Personality routine for WASM EH.
//
// Called at each catch site to determine which handler matches. Sets
// result_selector in __wasm_lpad_context which the compiler reads to dispatch
// to the correct catch clause.
//
// Setting result_selector = 1 matches the first catch clause. For MLX this
// is sufficient: exceptions are std::runtime_error caught by
// catch(const std::exception&). For full type-based dispatch, this would
// need to read the LSDA and do __dynamic_cast checks.
int _Unwind_CallPersonality(void* exception_object) {
  (void)exception_object;
  __wasm_lpad_context.result_selector = 1;
  return 0;
}

} // extern "C"

#endif // WEBGPU_BACKEND_WASI_IMPORT
