// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null;
const loadErrors = [];

const isMusl = () => {
  let musl = false;
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem();
    if (musl === null) {
      musl = isMuslFromReport();
    }
    if (musl === null) {
      musl = isMuslFromChildProcess();
    }
  }
  return musl;
};

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-');

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl');
  } catch {
    return null;
  }
};

const isMuslFromReport = () => {
  let report = null;
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true;
    report = process.report.getReport();
  }
  if (!report) {
    return null;
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false;
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true;
    }
  }
  return false;
};

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl');
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false;
  }
};

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err);
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.android-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-android-arm64');
        const bindingPackageVersion = require('@mlx-node/core-android-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./mlx-core.android-arm-eabi.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-android-arm-eabi');
        const bindingPackageVersion = require('@mlx-node/core-android-arm-eabi/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`));
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (
        process.config?.variables?.shlib_suffix === 'dll.a' ||
        process.config?.variables?.node_target_type === 'shared_library'
      ) {
        try {
          return require('./mlx-core.win32-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-win32-x64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-win32-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.win32-x64-msvc.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-win32-x64-msvc');
          const bindingPackageVersion = require('@mlx-node/core-win32-x64-msvc/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./mlx-core.win32-ia32-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-win32-ia32-msvc');
        const bindingPackageVersion = require('@mlx-node/core-win32-ia32-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.win32-arm64-msvc.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-win32-arm64-msvc');
        const bindingPackageVersion = require('@mlx-node/core-win32-arm64-msvc/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`));
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./mlx-core.darwin-universal.node');
    } catch (e) {
      loadErrors.push(e);
    }
    try {
      const binding = require('@mlx-node/core-darwin-universal');
      const bindingPackageVersion = require('@mlx-node/core-darwin-universal/package.json').version;
      if (
        bindingPackageVersion !== '0.0.7' &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
        process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
      ) {
        throw new Error(
          `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
        );
      }
      return binding;
    } catch (e) {
      loadErrors.push(e);
    }
    if (process.arch === 'x64') {
      try {
        return require('./mlx-core.darwin-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-darwin-x64');
        const bindingPackageVersion = require('@mlx-node/core-darwin-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.darwin-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-darwin-arm64');
        const bindingPackageVersion = require('@mlx-node/core-darwin-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`));
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./mlx-core.freebsd-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-freebsd-x64');
        const bindingPackageVersion = require('@mlx-node/core-freebsd-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.freebsd-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-freebsd-arm64');
        const bindingPackageVersion = require('@mlx-node/core-freebsd-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`));
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-x64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-x64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-x64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-x64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-x64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-x64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-arm64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-arm64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-arm-musleabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm-musleabihf');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm-musleabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-arm-gnueabihf.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-arm-gnueabihf');
          const bindingPackageVersion = require('@mlx-node/core-linux-arm-gnueabihf/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-loong64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-loong64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-loong64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-loong64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-loong64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-loong64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./mlx-core.linux-riscv64-musl.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-riscv64-musl');
          const bindingPackageVersion = require('@mlx-node/core-linux-riscv64-musl/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      } else {
        try {
          return require('./mlx-core.linux-riscv64-gnu.node');
        } catch (e) {
          loadErrors.push(e);
        }
        try {
          const binding = require('@mlx-node/core-linux-riscv64-gnu');
          const bindingPackageVersion = require('@mlx-node/core-linux-riscv64-gnu/package.json').version;
          if (
            bindingPackageVersion !== '0.0.7' &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
            process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
          ) {
            throw new Error(
              `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
            );
          }
          return binding;
        } catch (e) {
          loadErrors.push(e);
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./mlx-core.linux-ppc64-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-linux-ppc64-gnu');
        const bindingPackageVersion = require('@mlx-node/core-linux-ppc64-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./mlx-core.linux-s390x-gnu.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-linux-s390x-gnu');
        const bindingPackageVersion = require('@mlx-node/core-linux-s390x-gnu/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`));
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./mlx-core.openharmony-arm64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-openharmony-arm64');
        const bindingPackageVersion = require('@mlx-node/core-openharmony-arm64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./mlx-core.openharmony-x64.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-openharmony-x64');
        const bindingPackageVersion = require('@mlx-node/core-openharmony-x64/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./mlx-core.openharmony-arm.node');
      } catch (e) {
        loadErrors.push(e);
      }
      try {
        const binding = require('@mlx-node/core-openharmony-arm');
        const bindingPackageVersion = require('@mlx-node/core-openharmony-arm/package.json').version;
        if (
          bindingPackageVersion !== '0.0.7' &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK &&
          process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0'
        ) {
          throw new Error(
            `Native binding package version mismatch, expected 0.0.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`,
          );
        }
        return binding;
      } catch (e) {
        loadErrors.push(e);
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`));
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`));
  }
}

nativeBinding = requireNative();

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null;
  let wasiBindingError = null;
  try {
    wasiBinding = require('./mlx-core.wasi.cjs');
    nativeBinding = wasiBinding;
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err;
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@mlx-node/core-wasm32-wasi');
      nativeBinding = wasiBinding;
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err;
        } else {
          wasiBindingError.cause = err;
        }
        loadErrors.push(err);
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error');
    error.cause = wasiBindingError;
    throw error;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err;
          return cur;
        }),
      },
    );
  }
  throw new Error(`Failed to load native binding`);
}

module.exports = nativeBinding;
module.exports.BatchGenerationResult = nativeBinding.BatchGenerationResult;
module.exports.ChatStreamHandle = nativeBinding.ChatStreamHandle;
module.exports.DocLayoutModel = nativeBinding.DocLayoutModel;
module.exports.PPDocLayoutV3Model = nativeBinding.PPDocLayoutV3Model;
module.exports.DocOrientationModel = nativeBinding.DocOrientationModel;
module.exports.DocUnwarpModel = nativeBinding.DocUnwarpModel;
module.exports.Gemma4Model = nativeBinding.Gemma4Model;
module.exports.GenerationResult = nativeBinding.GenerationResult;
module.exports.GrpoTrainingEngine = nativeBinding.GrpoTrainingEngine;
module.exports.GRPOTrainingEngine = nativeBinding.GRPOTrainingEngine;
module.exports.HarrierModel = nativeBinding.HarrierModel;
module.exports.Lfm2Model = nativeBinding.Lfm2Model;
module.exports.MxArray = nativeBinding.MxArray;
module.exports.NativeRewardRegistry = nativeBinding.NativeRewardRegistry;
module.exports.OutputStore = nativeBinding.OutputStore;
module.exports.PromptCache = nativeBinding.PromptCache;
module.exports.QianfanOCRModel = nativeBinding.QianfanOCRModel;
module.exports.Qwen35Model = nativeBinding.Qwen35Model;
module.exports.Qwen3_5Model = nativeBinding.Qwen3_5Model;
module.exports.Qwen35MoeModel = nativeBinding.Qwen35MoeModel;
module.exports.Qwen3_5MoeModel = nativeBinding.Qwen3_5MoeModel;
module.exports.Qwen3Model = nativeBinding.Qwen3Model;
module.exports.Qwen3Tokenizer = nativeBinding.Qwen3Tokenizer;
module.exports.ResponseStore = nativeBinding.ResponseStore;
module.exports.SftTrainingEngine = nativeBinding.SftTrainingEngine;
module.exports.Tensor = nativeBinding.Tensor;
module.exports.TextDetModel = nativeBinding.TextDetModel;
module.exports.TextRecModel = nativeBinding.TextRecModel;
module.exports.VlmChatResult = nativeBinding.VlmChatResult;
module.exports.VLMChatResult = nativeBinding.VLMChatResult;
module.exports.VLModel = nativeBinding.VLModel;
module.exports.buildRewardOutputs = nativeBinding.buildRewardOutputs;
module.exports.BuiltinRewardType = nativeBinding.BuiltinRewardType;
module.exports.ChatRole = nativeBinding.ChatRole;
module.exports.convertForeignWeights = nativeBinding.convertForeignWeights;
module.exports.convertGgufToSafetensors = nativeBinding.convertGgufToSafetensors;
module.exports.convertModel = nativeBinding.convertModel;
module.exports.convertParquetToJsonl = nativeBinding.convertParquetToJsonl;
module.exports.createPaddleocrVlConfig = nativeBinding.createPaddleocrVlConfig;
module.exports.createQianfanOcrConfig = nativeBinding.createQianfanOcrConfig;
module.exports.createRandomQwen35Checkpoint = nativeBinding.createRandomQwen35Checkpoint;
module.exports.createRandomQwen35MoeCheckpoint = nativeBinding.createRandomQwen35MoeCheckpoint;
module.exports.createRandomQwen3Checkpoint = nativeBinding.createRandomQwen3Checkpoint;
module.exports.documentToXlsx = nativeBinding.documentToXlsx;
module.exports.DType = nativeBinding.DType;
module.exports.ElementType = nativeBinding.ElementType;
module.exports.formatDocument = nativeBinding.formatDocument;
module.exports.getExpectedWeightKeys = nativeBinding.getExpectedWeightKeys;
module.exports.getProfilingData = nativeBinding.getProfilingData;
module.exports.isProfilingEnabled = nativeBinding.isProfilingEnabled;
module.exports.memoryStats = nativeBinding.memoryStats;
module.exports.OutputFormat = nativeBinding.OutputFormat;
module.exports.parsePaddleResponse = nativeBinding.parsePaddleResponse;
module.exports.parseToolCallsFromText = nativeBinding.parseToolCallsFromText;
module.exports.parseVlmOutput = nativeBinding.parseVlmOutput;
module.exports.resetProfilingData = nativeBinding.resetProfilingData;
module.exports.saveToXlsx = nativeBinding.saveToXlsx;
module.exports.setProfilingEnabled = nativeBinding.setProfilingEnabled;
module.exports.__internal__ = nativeBinding.__internal__;
