/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Descriptor for a single GPU-resident tensor (from JS gpu-worker). */
export interface GpuTensorInfo {
  /** Weight name (e.g. "model.layers.0.mlp.gate_proj.weight") */
  name: string;
  /** Opaque WGPUBuffer handle (u32 on WASM) */
  handle: number;
  /** C++ dtype code: 0=f32, 1=f16, 2=bf16, 3=i32, 4=u32, 5=i8, 6=u8 */
  dtypeCode: number;
  /** Tensor shape dimensions */
  shape: Array<number>;
  /** GPU buffer size in bytes */
  byteSize: number;
  /** Whether bf16 data is packed 2-per-u32 (PackedBf16 storage mode) */
  packedBf16?: boolean | undefined | null;
}
export interface CpuTensorInfo {
  /** Weight name (e.g. "model.layers.0.mlp.gate_proj.weight") */
  name: string;
  /** WASM memory pointer (from malloc) where tensor bytes reside */
  ptr: number;
  /** C++ dtype code: 0=f32, 1=f16, 2=bf16, 3=i32, 4=u32, 6=u8 */
  dtypeCode: number;
  /** Tensor shape dimensions */
  shape: Array<number>;
  /** Tensor size in bytes */
  byteSize: number;
}
/**
 * Result from batch text generation
 *
 * Contains results for N prompts × G completions per prompt.
 * Results are stored flat in arrays of length N*G, where:
 * - First G elements are completions for prompt 0
 * - Next G elements are completions for prompt 1
 * - etc.
 */
export declare class BatchGenerationResult {
  /** Get all generated token arrays (N*G arrays) */
  get tokens(): Array<MxArray>;
  /** Get all log probability arrays (N*G arrays) */
  get logprobs(): Array<MxArray>;
  /** Get all decoded texts (N*G strings) */
  get texts(): Array<string>;
  /** Get finish reasons grouped by prompt (N arrays of G finish reasons) */
  get finishReasons(): Array<Array<string>>;
  /** Get token counts grouped by prompt (N arrays of G counts) */
  get tokenCounts(): Array<Array<number>>;
  /** Get number of prompts */
  get numPrompts(): number;
  /** Get group size (completions per prompt) */
  get groupSize(): number;
}

/** Handle returned by `chat_stream()` to control an in-progress streaming generation. */
export declare class ChatStreamHandle {
  cancel(): void;
}

/**
 * PP-DocLayoutV3 full model for document layout analysis.
 *
 * Combines HGNetV2 backbone, hybrid encoder, and RT-DETR decoder
 * with mask-enhanced attention and reading order prediction.
 *
 * Weights must be downloaded from `PaddlePaddle/PP-DocLayoutV3_safetensors` on HuggingFace.
 * The regular `PaddlePaddle/PP-DocLayoutV3` repo uses PaddlePaddle format and is not compatible.
 */
export declare class DocLayoutModel {
  /**
   * Load a PP-DocLayoutV3 model from a directory containing `config.json` and `model.safetensors`.
   *
   * The model directory should be cloned from `PaddlePaddle/PP-DocLayoutV3_safetensors` on HuggingFace.
   *
   * # Arguments
   * * `model_path` - Path to model directory
   *
   * # Returns
   * * Initialized DocLayoutModel ready for inference
   */
  static load(modelPath: string): DocLayoutModel;
  /**
   * Detect document layout elements in an image.
   *
   * # Arguments
   * * `image_data` - Encoded image bytes (PNG/JPEG)
   * * `threshold` - Optional confidence threshold (default 0.5)
   *
   * # Returns
   * * Vec of LayoutElements sorted by reading order
   */
  detect(imageData: Uint8Array, threshold?: number | undefined | null): Array<LayoutElement>;
}
export type PPDocLayoutV3Model = DocLayoutModel;

/**
 * PP-LCNet_x1_0 Document Orientation Classification model.
 *
 * Classifies document images into 4 orientation classes (0/90/180/270 degrees).
 * Uses depthwise separable convolutions with HardSwish activation.
 */
export declare class DocOrientationModel {
  /** Load a DocOrientationModel from a directory containing model.safetensors and config.json. */
  static load(modelPath: string): DocOrientationModel;
  /**
   * Classify the orientation of a document image.
   *
   * Returns the detected orientation angle (0, 90, 180, 270) and confidence.
   */
  classify(imageData: Buffer): OrientationResult;
  /**
   * Classify orientation and return the corrected (upright) image bytes.
   *
   * Returns classification result plus corrected PNG image bytes.
   */
  classifyAndRotate(imageData: Uint8Array): ClassifyRotateResult;
}

/**
 * UVDoc Document Unwarping model.
 *
 * Predicts a 2D displacement field and applies it to correct perspective
 * distortion in camera-captured documents.
 */
export declare class DocUnwarpModel {
  /** Load a DocUnwarpModel from a directory containing model.safetensors. */
  static load(modelPath: string): DocUnwarpModel;
  /** Unwarp a document image and return the corrected image bytes. */
  unwarp(imageData: Uint8Array): UnwarpResult;
}

/** Result from text generation with detailed metadata */
export declare class GenerationResult {
  /** Get the decoded text */
  get text(): string;
  /** Get the generated tokens */
  get tokens(): MxArray;
  /** Get the log probabilities */
  get logprobs(): MxArray;
  /** Get the finish reason ("stop", "length", or "repetition") */
  get finishReason(): 'stop' | 'length' | 'repetition';
  /** Get the number of tokens generated */
  get numTokens(): number;
}

export declare class MxArray {
  equal(other: MxArray): MxArray;
  notEqual(other: MxArray): MxArray;
  less(other: MxArray): MxArray;
  lessEqual(other: MxArray): MxArray;
  greater(other: MxArray): MxArray;
  greaterEqual(other: MxArray): MxArray;
  logicalAnd(other: MxArray): MxArray;
  logicalOr(other: MxArray): MxArray;
  logicalNot(): MxArray;
  where(x: MxArray, y: MxArray): MxArray;
  static fromInt32(data: Int32Array, shape: BigInt64Array): MxArray;
  static fromInt64(data: BigInt64Array, shape: BigInt64Array): MxArray;
  static fromUint32(data: Uint32Array, shape: BigInt64Array): MxArray;
  static fromFloat32(data: Float32Array, shape: BigInt64Array): MxArray;
  static zeros(shape: BigInt64Array, dtype?: DType | undefined | null): MxArray;
  static scalarFloat(value: number): MxArray;
  static scalarInt(value: number): MxArray;
  static ones(shape: BigInt64Array, dtype?: DType | undefined | null): MxArray;
  static full(shape: BigInt64Array, fillValue: number | MxArray, dtype?: DType | undefined | null): MxArray;
  static linspace(
    start: number,
    stop: number,
    num?: number | undefined | null,
    dtype?: DType | undefined | null,
  ): MxArray;
  static eye(
    n: number,
    m?: number | undefined | null,
    k?: number | undefined | null,
    dtype?: DType | undefined | null,
  ): MxArray;
  static arange(
    start: number,
    stop: number,
    step?: number | undefined | null,
    dtype?: DType | undefined | null,
  ): MxArray;
  astype(dtype: DType): MxArray;
  /**
   * Create a copy of this array with a new handle.
   * This is useful for parameter loading to avoid handle aliasing issues.
   */
  copy(): MxArray;
  eval(): void;
  evalAsync(): Promise<undefined>;
  size(): bigint;
  ndim(): number;
  shape(): BigInt64Array;
  /**
   * Get a single dimension from the array shape without copying the entire shape
   * This is more efficient when you only need one dimension
   *
   * Note: axis is u32 because NAPI doesn't support usize, but internally converted to usize
   */
  shapeAt(axis: number): number;
  /**
   * Get batch and sequence length for 2D arrays (common pattern in transformers)
   * More efficient than calling shape() and extracting dimensions
   */
  getBatchSeqLen(): Array<number>;
  /**
   * Get batch, sequence length, and hidden size for 3D arrays (common pattern in transformers)
   * More efficient than calling shape() and extracting dimensions
   */
  getBatchSeqHidden(): Array<number>;
  dtype(): DType;
  /**
   * Copy entire array from GPU to CPU as Float32Array
   *
   * **PERFORMANCE WARNING**: This triggers a FULL GPU->CPU memory transfer!
   *
   * **Performance impact**:
   * - Forces evaluation of lazy operations
   * - Copies entire array from GPU to CPU memory
   * - Can be extremely slow for large arrays
   *
   * **Use sparingly**:
   * - Prefer `item_float32()` for scalars
   * - Prefer `item_at_float32(index)` for single elements
   * - Only use when you truly need all array data on CPU
   *
   * **Acceptable use cases**:
   * - Test validation and assertions
   * - CPU-only operations (e.g., sorting for quantiles)
   * - Final output extraction
   */
  toFloat32(): Float32Array;
  /**
   * Copy entire array from GPU to CPU as Int32Array
   *
   * **PERFORMANCE WARNING**: This triggers a FULL GPU->CPU memory transfer!
   *
   * See `to_float32()` documentation for performance implications and alternatives.
   * Prefer `item_int32()` for scalars.
   */
  toInt32(): Int32Array;
  /**
   * Copy entire array from GPU to CPU as Uint32Array
   *
   * **PERFORMANCE WARNING**: This triggers a FULL GPU->CPU memory transfer!
   *
   * See `to_float32()` documentation for performance implications and alternatives.
   */
  toUint32(): Uint32Array;
  logSoftmax(axis: number): MxArray;
  exp(): MxArray;
  log(): MxArray;
  clip(minimum?: number | undefined | null, maximum?: number | undefined | null): MxArray;
  minimum(other: MxArray): MxArray;
  maximum(other: MxArray): MxArray;
  add(other: MxArray): MxArray;
  sub(other: MxArray): MxArray;
  mul(other: MxArray): MxArray;
  div(other: MxArray): MxArray;
  addScalar(value: number): MxArray;
  mulScalar(value: number): MxArray;
  subScalar(value: number): MxArray;
  divScalar(value: number): MxArray;
  matmul(other: MxArray): MxArray;
  /**
   * Fused matrix multiply-add: D = beta * C + alpha * (self @ B)
   * where self is A. More efficient than separate matmul and add operations.
   * Default: alpha=1.0, beta=1.0, giving D = C + (self @ B)
   */
  addmm(c: MxArray, b: MxArray, alpha?: number | undefined | null, beta?: number | undefined | null): MxArray;
  abs(): MxArray;
  negative(): MxArray;
  sign(): MxArray;
  sqrt(): MxArray;
  square(): MxArray;
  power(other: MxArray): MxArray;
  sin(): MxArray;
  cos(): MxArray;
  tan(): MxArray;
  sinh(): MxArray;
  cosh(): MxArray;
  tanh(): MxArray;
  floor(): MxArray;
  ceil(): MxArray;
  round(): MxArray;
  floorDivide(other: MxArray): MxArray;
  remainder(other: MxArray): MxArray;
  reciprocal(): MxArray;
  arcsin(): MxArray;
  arccos(): MxArray;
  arctan(): MxArray;
  log10(): MxArray;
  log2(): MxArray;
  log1p(): MxArray;
  /**
   * Element-wise check for NaN values
   *
   * Returns a boolean array where True indicates the element is NaN.
   * This is a GPU-native operation that avoids CPU data transfer.
   */
  isnan(): MxArray;
  /**
   * Element-wise check for Inf values
   *
   * Returns a boolean array where True indicates the element is +Inf or -Inf.
   * This is a GPU-native operation that avoids CPU data transfer.
   */
  isinf(): MxArray;
  /**
   * Element-wise check for finite values
   *
   * Returns a boolean array where True indicates the element is finite (not NaN and not Inf).
   * This is a GPU-native operation that avoids CPU data transfer.
   */
  isfinite(): MxArray;
  static randomUniform(shape: BigInt64Array, low: number, high: number, dtype?: DType | undefined | null): MxArray;
  static randomNormal(shape: BigInt64Array, mean: number, std: number, dtype?: DType | undefined | null): MxArray;
  static randomBernoulli(shape: BigInt64Array, prob: number): MxArray;
  static randint(shape: BigInt64Array, low: number, high: number): MxArray;
  /**
   * Sample from categorical distribution
   * Takes logits and returns sampled indices
   */
  categorical(axis?: number | undefined | null): MxArray;
  sum(axes?: Int32Array | undefined | null, keepdims?: boolean | undefined | null): MxArray;
  mean(axes?: Int32Array | undefined | null, keepdims?: boolean | undefined | null): MxArray;
  argmax(axis: number, keepdims?: boolean | undefined | null): MxArray;
  argmin(axis: number, keepdims?: boolean | undefined | null): MxArray;
  max(axes?: Int32Array | undefined | null, keepdims?: boolean | undefined | null): MxArray;
  min(axes?: Int32Array | undefined | null, keepdims?: boolean | undefined | null): MxArray;
  prod(axes?: Int32Array | undefined | null, keepdims?: boolean | undefined | null): MxArray;
  var(
    axes?: Int32Array | undefined | null,
    keepdims?: boolean | undefined | null,
    ddof?: number | undefined | null,
  ): MxArray;
  std(
    axes?: Int32Array | undefined | null,
    keepdims?: boolean | undefined | null,
    ddof?: number | undefined | null,
  ): MxArray;
  logsumexp(axes?: Int32Array | undefined | null, keepdims?: boolean | undefined | null): MxArray;
  cumsum(axis: number): MxArray;
  cumprod(axis: number): MxArray;
  reshape(shape: BigInt64Array): MxArray;
  transpose(axes?: Int32Array | undefined | null): MxArray;
  take(indices: MxArray, axis: number): MxArray;
  takeAlongAxis(indices: MxArray, axis: number): MxArray;
  /**
   * Put values into array at specified indices along an axis
   * Equivalent to: result = array.copy(); result[..., indices] = values
   * This matches MLX's put_along_axis for efficient in-place-style updates
   */
  putAlongAxis(indices: MxArray, values: MxArray, axis: number): MxArray;
  slice(starts: BigInt64Array, stops: BigInt64Array): MxArray;
  /**
   * Concatenate two arrays along an axis
   * Optimized for the common binary concatenation case
   */
  static concatenate(a: MxArray, b: MxArray, axis: number): MxArray;
  /**
   * Concatenate multiple arrays along an axis
   * For concatenating 3 or more arrays
   */
  static concatenateMany(arrays: Array<MxArray>, axis?: number | undefined | null): MxArray;
  sort(axis?: number | undefined | null): MxArray;
  argsort(axis?: number | undefined | null): MxArray;
  partition(kth: number, axis?: number | undefined | null): MxArray;
  argpartition(kth: number, axis?: number | undefined | null): MxArray;
  static stack(arrays: Array<MxArray>, axis?: number | undefined | null): MxArray;
  pad(padWidth: Int32Array, constantValue: number): MxArray;
  roll(shift: number, axis: number): MxArray;
  split(indicesOrSections: number, axis?: number | undefined | null): Array<MxArray>;
  tile(reps: Int32Array): MxArray;
  repeat(repeats: number, axis: number): MxArray;
  squeeze(axes?: Int32Array | undefined | null): MxArray;
  expandDims(axis: number): MxArray;
  broadcastTo(shape: BigInt64Array): MxArray;
}

/**
 * Opaque handle to KV cache state from a previous chat() call.
 *
 * Pass this back to the next chat() call via `model.setCache(cache)`
 * to enable incremental prefill — only new tokens since the last turn
 * are processed, avoiding redundant computation.
 *
 * Created internally by the model when `reuseCache: true` (default).
 * Extract via `model.takeCache()`, restore via `model.setCache(cache)`.
 */
export declare class PromptCache {
  /** Number of tokens stored in this cache. */
  get tokenCount(): number;
  /** Whether this cache has been consumed (caches moved out). */
  get isEmpty(): boolean;
  /** Release GPU memory held by this cache. */
  dispose(): void;
}

/**
 * Qianfan-OCR Vision-Language Model (InternVL architecture).
 *
 * Combines InternViT vision encoder, MLP bridge with pixel shuffle,
 * and Qwen3 language model for OCR and document understanding.
 */
export declare class QianfanOCRModel {
  /** Create a new QianfanOCRModel from config (uninitialized, no weights). */
  constructor(config: QianfanOcrConfig);
  /** Returns true if weights have been loaded. */
  get isInitialized(): boolean;
  /**
   * Load a QianfanOCRModel from a directory.
   *
   * Reads config.json, loads SafeTensors weights (single or sharded),
   * builds vision encoder, bridge, and language model, and loads tokenizer.
   */
  static load(modelPath: string): Promise<QianfanOCRModel>;
  /**
   * Chat with the model.
   *
   * High-level API: processes images, formats prompt, generates, and decodes.
   */
  chat(messages: Array<ChatMessage>, config?: ChatConfig | undefined | null): Promise<QianfanChatResult>;
  /**
   * Streaming chat with the model.
   *
   * Same as chat() but emits tokens incrementally via callback.
   */
  chatStream(
    messages: ChatMessage[],
    config: ChatConfig | null,
    callback: (err: Error | null, chunk: ChatStreamChunk) => void,
  ): Promise<ChatStreamHandle>;
  /**
   * Generate text tokens given pre-tokenized input.
   *
   * Lower-level API — prefer chat() for typical usage.
   */
  generate(
    inputIds: MxArray,
    maxNewTokens?: number | undefined | null,
    temperature?: number | undefined | null,
  ): Promise<Array<number>>;
  /** Reset KV caches and token history. */
  resetCaches(): void;
}

/**
 * Qwen3.5 Model -- hybrid linear/full attention with optional MoE.
 *
 * Uses interior mutability (RwLock) for layers, final_norm, lm_head, and caches
 * to allow async generation via spawn_blocking without blocking the Node.js event loop.
 * This matches the pattern used by Qwen3Model.
 */
export declare class Qwen35Model {
  /** Create a new Qwen3.5 model with the given configuration. */
  constructor(config: Qwen35Config);
  /** Initialize caches for incremental generation. */
  initCaches(): void;
  /** Reset all caches. */
  resetCaches(): void;
  /**
   * Take the KV cache from the model, returning a `PromptCache` handle.
   *
   * The cache is moved out of the model — calling `takeCache()` twice
   * returns `null` the second time. Pass the cache back via `setCache()`
   * before the next `chat()` call for incremental prefill.
   */
  takeCache(): PromptCache | null;
  /**
   * Restore a previously taken `PromptCache` into the model.
   *
   * On the next `chat()` call with `reuseCache: true`, the model will
   * prefix-match the new tokens against the cache and only prefill the delta.
   */
  setCache(cache: PromptCache): void;
  /**
   * Forward pass through the model.
   *
   * # Arguments
   * * `input_ids` - Token IDs [B, T]
   *
   * # Returns
   * Logits [B, T, vocab_size]
   */
  forward(inputIds: MxArray): MxArray;
  /** Forward pass with cache for incremental generation. */
  forwardWithCache(inputIds: MxArray): MxArray;
  /**
   * Load a pretrained model from a directory.
   *
   * Expects the directory to contain:
   * - config.json
   * - model.safetensors (or model-*.safetensors)
   * - tokenizer.json + tokenizer_config.json
   */
  static load(path: string): Promise<Qwen35Model>;
  /**
   * Load a model from in-memory buffers (works in both Node.js and browser).
   *
   * # Arguments
   * * `config_json` - Contents of config.json as a string
   * * `weight_buffers` - SafeTensors file contents as Buffers
   * * `tokenizer_json` - Contents of tokenizer.json as a string
   * Load a model from in-memory buffers (works in both Node.js and browser).
   */
  static loadFromMemory(configJson: string, weightBuffers: Array<Buffer>, tokenizerJson: string): Qwen35Model;
  /**
   * Load a model from pre-created GPU buffers (zero-copy, for browser WebGPU).
   *
   * The JS side parses SafeTensors headers, creates GPU buffers directly from the
   * fetch ArrayBuffer, and passes the buffer handles here. No weight data touches
   * WASM linear memory.
   */
  static loadFromGpuBuffers(
    configJson: string,
    gpuTensors: Array<GpuTensorInfo>,
    tokenizerJson: string,
    tokenizerConfigJson?: string | undefined | null,
  ): Qwen35Model;
  /** Store config and tokenizer strings before tensor accumulation (call before addCpuTensor). */
  static setCpuModelConfig(
    configJson: string,
    tokenizerJson: string,
    tokenizerConfigJson?: string | undefined | null,
  ): void;
  /** Add one CPU-resident tensor to the accumulator. C++ copies data from ptr immediately. */
  static addCpuTensor(name: string, ptr: number, byteSize: number, shape: Array<number>, dtypeCode: number): void;
  /** Debug probe: test NAPI call after memory growth. step 0=noop, 1=check config, 2=check tensors, 3=full build */
  static buildModelDebugProbe(step: number): string;
  /** Build model from stored config and accumulated CPU tensors (async — dispatched to emnapi worker). */
  static buildModelFromCpuTensors(): Promise<Qwen35Model>;
  /**
   * Generate text from a prompt token sequence.
   *
   * Runs generation on a worker thread via spawn_blocking to avoid
   * blocking the Node.js event loop.
   */
  generate(promptTokens: MxArray, config: Qwen35GenerationConfig): Promise<Qwen35GenerationResult>;
  /**
   * Chat API with tool calling support.
   *
   * Runs tokenization + generation on a worker thread via spawn_blocking
   * to avoid blocking the Node.js event loop.
   */
  chat(messages: Array<ChatMessage>, config?: ChatConfig | undefined | null): Promise<ChatResult>;
  /**
   * Synchronous chat for WASM.
   *
   * NAPI-RS `async fn` dispatches through emnapi's worker thread pool where
   * asyncify can't yield, causing `poll_instance()` to deadlock. This sync
   * version bypasses the async machinery entirely. Safe because WASM user
   * code is single-threaded (no concurrent `chat()` calls possible).
   */
  chatSync(messages: Array<ChatMessage>, config?: ChatConfig | undefined | null): ChatResult;
  /**
   * Streaming chat API with tool calling support.
   *
   * Same as `chat()` but streams tokens one-by-one via the callback.
   * Returns a `ChatStreamHandle` immediately; generation runs in background.
   * Call `handle.cancel()` to abort generation early.
   */
  chatStream(
    messages: ChatMessage[],
    config: ChatConfig | null,
    callback: (err: Error | null, chunk: ChatStreamChunk) => void,
  ): Promise<ChatStreamHandle>;
  /** Get the number of parameters in the model. */
  numParameters(): number;
  /**
   * Save the model weights and configuration to a directory.
   *
   * This saves:
   * - config.json: Model configuration (with model_type for detectModelType)
   * - weights.safetensors: Full model weights in SafeTensors format
   * - weights.mlx: Parameter metadata (for reference)
   *
   * # Arguments
   * * `save_path` - Directory to save the model
   */
  saveModel(savePath: string): Promise<undefined>;
}
export type Qwen3_5Model = Qwen35Model;

/**
 * Qwen3.5 MoE Model -- hybrid linear/full attention with Mixture-of-Experts.
 *
 * Supports C++ MoE forward path (non-compiled, builds fresh graph per step)
 * when weights are registered via `register_moe_weights_with_cpp`.
 * Falls back to Rust forward_inner path for test models without stored weights.
 */
export declare class Qwen35MoeModel {
  constructor(config: Qwen35MoeConfig);
  /**
   * Take the KV cache from the model, returning a `PromptCache` handle.
   *
   * The cache is moved out of the model — calling `takeCache()` twice
   * returns `null` the second time. Pass the cache back via `setCache()`
   * before the next `chat()` call for incremental prefill.
   */
  takeCache(): PromptCache | null;
  /**
   * Restore a previously taken `PromptCache` into the model.
   *
   * On the next `chat()` call with `reuseCache: true`, the model will
   * prefix-match the new tokens against the cache and only prefill the delta.
   */
  setCache(cache: PromptCache): void;
  initCaches(): void;
  resetCaches(): void;
  forward(inputIds: MxArray): MxArray;
  forwardWithCache(inputIds: MxArray): MxArray;
  static load(path: string): Promise<Qwen35MoeModel>;
  generate(promptTokens: MxArray, config: Qwen35MoeGenerationConfig): Promise<Qwen35MoeGenerationResult>;
  chat(messages: Array<ChatMessage>, config?: ChatConfig | undefined | null): Promise<ChatResult>;
  /**
   * Streaming chat API with tool calling support.
   *
   * Same as `chat()` but streams tokens one-by-one via the callback.
   * Returns a `ChatStreamHandle` immediately; generation runs in background.
   * Call `handle.cancel()` to abort generation early.
   */
  chatStream(
    messages: ChatMessage[],
    config: ChatConfig | null,
    callback: (err: Error | null, chunk: ChatStreamChunk) => void,
  ): Promise<ChatStreamHandle>;
  numParameters(): number;
  /**
   * Save the model weights and configuration to a directory.
   *
   * This saves:
   * - config.json: Model configuration (with model_type for detectModelType)
   * - weights.safetensors: Full model weights in SafeTensors format
   * - weights.mlx: Parameter metadata (for reference)
   *
   * # Arguments
   * * `save_path` - Directory to save the model
   */
  saveModel(savePath: string): Promise<undefined>;
}
export type Qwen3_5MoeModel = Qwen35MoeModel;

/**
 * Qwen3 Model with automatic differentiation support
 *
 * Uses interior mutability (RwLock) for layers, final_norm, and lm_head
 * to allow gradient application without deep cloning the model.
 * This eliminates the previous ~4GB memory overhead from clone_for_session().
 */
export declare class Qwen3Model {
  /** Create a new Qwen3 model with the given configuration */
  constructor(config: Qwen3Config);
  /**
   * Reset the KV cache used for cache reuse across chat() calls.
   * Call this when starting a new conversation to ensure a full prefill.
   */
  resetCache(): void;
  /**
   * Forward pass through the model
   *
   * # Arguments
   * * `input_ids` - Token IDs, shape: [batch_size, seq_len]
   *
   * # Returns
   * * Logits, shape: [batch_size, seq_len, vocab_size]
   */
  forward(inputIds: MxArray): MxArray;
  /**
   * Initialize KV caches for incremental generation
   *
   * Creates one KV cache per transformer layer. Call this before starting generation.
   */
  initKvCaches(): void;
  /**
   * Reset all KV caches
   *
   * Clears cached key-value states. Call this between different generation sequences.
   */
  resetKvCaches(): void;
  /** Check if paged attention is enabled for this model */
  hasPagedAttention(): boolean;
  /**
   * Get paged attention memory statistics (if enabled)
   *
   * Returns memory usage statistics for the paged KV cache.
   */
  pagedCacheStats(): PagedCacheStats | null;
  /**
   * Get scheduler statistics (if paged attention is enabled)
   *
   * Returns the number of waiting, running, and completed sequences.
   */
  schedulerStats(): SchedulerStatsNapi | null;
  /**
   * Forward pass with KV caching for incremental generation
   *
   * # Arguments
   * * `input_ids` - Token IDs, shape: [batch_size, seq_len]
   * * `use_cache` - Whether to use KV caching (must call init_kv_caches() first)
   *
   * # Returns
   * * Logits, shape: [batch_size, seq_len, vocab_size]
   */
  forwardWithCache(inputIds: MxArray, useCache: boolean): MxArray;
  /**
   * Forward pass with paged attention for memory-efficient inference.
   *
   * This method uses block-based KV cache management via Metal kernels for:
   * - Variable-length sequences with efficient memory usage
   * - Continuous batching with dynamic batch composition
   * - Long context support beyond GPU memory limits
   *
   * # Arguments
   * * `input_ids` - Token IDs, shape: [num_seqs, 1] for decode
   * * `slot_mapping` - Slot indices for cache updates, shape: [num_seqs]
   * * `seq_ids` - Sequence IDs in the batch (for looking up block tables/context lens)
   * * `positions` - Token positions for RoPE, shape: [num_seqs] (per-sequence positions)
   *
   * # Returns
   * * Logits, shape: [num_seqs, 1, vocab_size] for decode
   */
  forwardPaged(inputIds: MxArray, slotMapping: MxArray, seqIds: Array<number>, positions: MxArray): MxArray;
  /**
   * Prefill a sequence using standard attention and write K/V to paged cache.
   *
   * This method should be called before `step_paged_generation()` for each
   * new prompt. It runs the full forward pass using standard attention
   * (which is faster for long sequences), then writes the K/V cache to
   * the paged cache for subsequent decode steps.
   *
   * # Arguments
   * * `prompt_tokens` - Token IDs for the prompt (as u32 array)
   * * `seq_id` - Sequence ID (obtained from scheduler)
   *
   * # Returns
   * * Logits for the last token, shape: [1, vocab_size]
   */
  prefillPaged(promptTokens: Array<number>, seqId: number): MxArray;
  /**
   * Add a request to the paged attention scheduler.
   *
   * The scheduler queues requests and allocates blocks for KV cache.
   * Use `step_paged_generation()` to process the scheduled batch.
   *
   * Note: The actual sequence ID is assigned during scheduling, not when the
   * request is added. Use the `request_id` to track your requests through
   * the generation process.
   *
   * # Arguments
   * * `request_id` - Unique identifier for the request (returned in outputs)
   * * `prompt_tokens` - Token IDs for the prompt
   * * `max_new_tokens` - Maximum new tokens to generate
   * * `priority` - Optional priority (higher = scheduled first)
   *
   * # Returns
   * * Number of pending requests in the queue
   */
  addPagedRequest(
    requestId: string,
    promptTokens: Array<number>,
    maxNewTokens: number,
    priority?: number | undefined | null,
  ): number;
  /**
   * Schedule and execute one step of paged generation.
   *
   * This method:
   * 1. Schedules the next batch of sequences
   * 2. Runs forward pass with paged attention
   * 3. Samples next tokens
   * 4. Returns the generated tokens for each sequence
   *
   * # Arguments
   * * `config` - Generation configuration (temperature, top_k, etc.)
   *
   * # Returns
   * * `PagedGenerationStep` with token outputs for each sequence
   */
  stepPagedGeneration(config?: GenerationConfig | undefined | null): PagedGenerationStep | null;
  /**
   * Get completed sequences from the scheduler.
   *
   * Call this after `step_paged_generation()` returns outputs with `is_finished: true`.
   */
  getCompletedSequences(): Array<PagedCompletedSequence>;
  /** Check if the scheduler has pending work. */
  hasPagedWork(): boolean;
  /** Get model configuration */
  getConfig(): Qwen3Config;
  /**
   * Generate tokens using speculative decoding with a draft model.
   *
   * Speculative decoding uses a smaller draft model to generate tokens speculatively,
   * then verifies them with the target model in a single forward pass. This can achieve
   * 2-3x speedup when the draft model has high acceptance rate.
   *
   * # Algorithm
   * 1. Draft model generates N tokens speculatively (cheap forward passes)
   * 2. Target model (self) verifies all N tokens in one forward pass
   * 3. Accept/reject using rejection sampling
   * 4. On rejection, resample from adjusted distribution
   * 5. Rewind caches and continue
   *
   * # Arguments
   * * `draft_model` - Smaller model for speculative generation (should share tokenizer)
   * * `input_ids` - Input token IDs [1, seq_len]
   * * `config` - Generation configuration (includes num_draft_tokens)
   *
   * # Returns
   * GenerationResult with tokens, logprobs, and speculative stats in finish_reason
   *
   * # Example (TypeScript)
   * ```typescript
   * const targetModel = await loadModel('qwen3-7b');
   * const draftModel = await loadModel('qwen3-0.5b');
   *
   * const result = targetModel.generateSpeculativeSync(draftModel, inputIds, {
   *   numDraftTokens: 5,
   *   maxNewTokens: 100,
   *   temperature: 0.7,
   * });
   * ```
   */
  generateSpeculativeSync(
    draftModel: Qwen3Model,
    inputIds: MxArray,
    config?: GenerationConfig | undefined | null,
  ): GenerationResult;
  /** Count total number of parameters in the model */
  numParameters(): number;
  /**
   * Get all model parameters as a dictionary mapping names to arrays
   *
   * This matches the TypeScript API for compatibility
   */
  getParameters(): Record<string, MxArray>;
  /** Load parameters from a dictionary */
  loadParameters(params: Record<string, MxArray>): void;
  /**
   * Compute forward pass and loss (for evaluation)
   *
   * # Arguments
   * * `input_ids` - Input token IDs, shape: [batch_size, seq_len]
   * * `labels` - Target token IDs, shape: [batch_size, seq_len]
   *
   * # Returns
   * * Scalar loss value
   */
  computeLoss(inputIds: MxArray, labels: MxArray): MxArray;
  /**
   * Compute loss and gradients using a hybrid approach
   *
   * This implementation computes gradients for the output layers and uses
   * numerical approximations for other parameters. This is sufficient to
   * demonstrate that training works while we build out full MLX autograd integration.
   *
   * # Arguments
   * * `input_ids` - Input token IDs, shape: [batch_size, seq_len]
   * * `labels` - Target token IDs, shape: [batch_size, seq_len]
   *
   * # Returns
   * * A tuple of (loss, gradients_dict) where gradients_dict maps parameter names to gradient arrays
   *
   * # Phase 6A Status
   * Current implementation computes:
   * - ✅ Exact gradients for LM head (output layer)
   * - ⚠吅 Numerical approximations for other layers
   *
   * Future: Full MLX autograd will compute exact gradients for all 250+ parameters
   */
  computeLossAndGradients(inputIds: MxArray, labels: MxArray): [MxArray, Record<string, MxArray>];
  /**
   * Accumulate gradients into existing gradient dictionary
   *
   * This is a helper method for gradient accumulation. It adds new_gradients
   * to accumulated_gradients element-wise.
   *
   * # Arguments
   * * `accumulated_gradients` - Existing accumulated gradients (will be modified in-place conceptually, but returns new dict)
   * * `new_gradients` - New gradients to add
   *
   * # Returns
   * * Updated gradient dictionary with accumulated values
   */
  static accumulateGradients(
    accumulatedGradients: Record<string, MxArray>,
    newGradients: Record<string, MxArray>,
  ): Record<string, MxArray>;
  /**
   * Apply gradients to model parameters
   *
   * # Arguments
   * * `gradients` - Dictionary mapping parameter names to gradient arrays
   * * `learning_rate` - Learning rate for gradient descent
   *
   * This performs a simple SGD update: param = param - lr * grad
   * Only updates parameters that have gradients; others remain unchanged.
   *
   * IMPORTANT: This function preserves the original dtype of parameters.
   * The learning rate scalar is cast to match param dtype to prevent
   * promotion to float32 during arithmetic operations.
   */
  applyGradients(gradients: Record<string, MxArray>, learningRate: number): void;
  /**
   * Text-to-text generation with integrated tokenization
   *
   * This is a high-level API that handles chat template formatting, tokenization,
   * generation, and decoding internally. It takes chat messages, applies the ChatML
   * template, generates tokens, and decodes them back to text.
   *
   * # Arguments
   * * `messages` - Array of chat messages with role and content
   * * `config` - Generation configuration
   *
   * # Returns
   * * GenerationResult with text, tokens, logprobs, finish reason, and token count
   *
   * # Example
   * ```typescript
   * const model = await Qwen3Model.load("path/to/model");
   * const messages = [
   *   { role: "user", content: "What is 2+2?" }
   * ];
   * const result = await model.generate(messages, {
   *   maxNewTokens: 50,
   *   temperature: 0.8,
   *   topP: 0.95,
   * });
   * console.log(result.text); // Decoded text output
   * console.log(result.tokens); // Token IDs (for GRPO)
   * console.log(result.logprobs); // Log probabilities (for GRPO)
   * ```
   */
  generate(messages: Array<ChatMessage>, config?: GenerationConfig | undefined | null): Promise<GenerationResult>;
  /**
   * High-level chat API with structured response parsing
   *
   * The primary API for conversational AI. Handles:
   * - Chat message formatting with Jinja2 templates
   * - Tool/function calling with structured output
   * - Thinking extraction from `<think>` tags
   * - Clean response text with all special tags stripped
   *
   * ## `chat()` vs `generate()`
   *
   * | Feature | `chat()` | `generate()` |
   * |---------|----------|--------------|
   * | **Purpose** | Conversational AI with tools | Raw text generation |
   * | **Input** | Chat messages | Token IDs (MxArray) |
   * | **Tool Support** | Built-in parsing | None |
   * | **Thinking** | Extracts `<think>` content | Raw text only |
   * | **Output** | Structured `ChatResult` | Basic `GenerationResult` |
   * | **Use Case** | Chat apps, agents, assistants | Training, low-level control |
   *
   * ## When to use `chat()`
   * - Building conversational applications
   * - Need tool/function calling
   * - Want structured responses with thinking separated
   * - Working with chat message format
   *
   * ## When to use `generate()`
   * - Training and fine-tuning (need raw logprobs)
   * - Custom tokenization pipeline
   * - Low-level generation control
   * - Non-chat use cases
   *
   * # Arguments
   * * `messages` - Array of chat messages (user/assistant/system roles)
   * * `config` - Chat configuration including optional tools and generation params
   *
   * # Returns
   * * `ChatResult` containing:
   *   - `text`: Clean response (tool_call and think tags stripped)
   *   - `thinking`: Extracted chain-of-thought reasoning (or null)
   *   - `toolCalls`: Parsed tool calls with native JS object arguments
   *   - `finishReason`: "stop" | "length" | "tool_calls"
   *   - `rawText`: Original text before processing (for debugging)
   *
   * # Example
   * ```typescript
   * // Simple chat
   * const result = await model.chat(messages);
   * console.log(result.text);
   *
   * // With tools
   * const result = await model.chat(messages, {
   *   tools: [{ type: 'function', function: { name: 'get_weather' } }],
   *   maxNewTokens: 2048,
   *   temperature: 0.7,
   * });
   *
   * // Handle tool calls
   * for (const call of result.toolCalls) {
   *   if (call.status === 'ok') {
   *     console.log(call.name, call.arguments);  // Arguments is a JS object!
   *   }
   * }
   *
   * // Access thinking (chain-of-thought)
   * if (result.thinking) {
   *   console.log('Model reasoning:', result.thinking);
   * }
   * ```
   */
  chat(messages: Array<ChatMessage>, config?: ChatConfig | undefined | null): Promise<ChatResult>;
  /**
   * Generate multiple completions for multiple prompts in batch
   *
   * This is an optimized method for GRPO training that generates G completions
   * for each of N prompts. It performs all tokenization, generation, and decoding
   * in 3 blocking tasks instead of N*(1+2G) tasks.
   *
   * # Arguments
   * * `prompts` - Array of N prompt message arrays
   * * `group_size` - Number of completions (G) to generate per prompt
   * * `config` - Generation configuration (sampling params, etc.)
   *
   * # Returns
   * * BatchGenerationResult containing N*G completions with:
   *   - tokens: Flat array of N*G token arrays
   *   - logprobs: Flat array of N*G logprob arrays
   *   - texts: Flat array of N*G decoded texts
   *   - finish_reasons: N arrays of G finish reasons
   *   - token_counts: N arrays of G token counts
   *
   * # Performance
   * For N=10 prompts, G=8 completions:
   * - Old approach: N*(1 tokenize + G generate + G decode) = 10*(1+8+8) = 170 blocking tasks
   * - New approach: 1 tokenize + N*G generate + 1 decode = 1+80+1 = 82 blocking tasks (2.1x reduction)
   *
   * # Example
   * ```typescript
   * const result = await model.generateBatch(
   *   [messages1, messages2, ...], // N prompts
   *   8,                             // G completions per prompt
   *   config
   * );
   * ```
   */
  generateBatch(
    prompts: Array<Array<ChatMessage>>,
    groupSize: number,
    config?: GenerationConfig | undefined | null,
  ): Promise<BatchGenerationResult>;
  /**
   * Decode token IDs to text using the internal tokenizer
   *
   * Helper method for decoding generated tokens. The model must have been loaded
   * via load() to have a tokenizer available.
   *
   * # Arguments
   * * `token_ids` - Token IDs to decode as Uint32Array
   * * `skip_special_tokens` - Whether to skip special tokens (default: true)
   *
   * # Returns
   * * Decoded text string
   */
  decode(tokenIds: Uint32Array, skipSpecialTokens?: boolean | undefined | null): Promise<string>;
  /**
   * Apply chat template and encode to token IDs
   *
   * Formats messages using ChatML format (or Jinja2 template with tools) and encodes to tokens.
   * The model must have been loaded via load() to have a tokenizer available.
   *
   * # Arguments
   * * `messages` - Array of chat messages
   * * `add_generation_prompt` - Whether to add generation prompt (default: true)
   * * `tools` - Optional array of tool definitions for function calling
   * * `enable_thinking` - Optional flag to enable thinking mode (<think> tags)
   *
   * # Returns
   * * Encoded token IDs as Uint32Array
   */
  applyChatTemplate(
    messages: Array<ChatMessage>,
    addGenerationPrompt?: boolean | undefined | null,
    tools?: Array<ToolDefinition> | undefined | null,
    enableThinking?: boolean | undefined | null,
  ): Promise<Uint32Array>;
}

/** Qwen3 Tokenizer class with NAPI bindings */
export declare class Qwen3Tokenizer {
  /**
   * Load tokenizer from tokenizer.json file
   *
   * # Arguments
   * * `path` - Path to tokenizer.json file (default: "../.cache/assets/tokenizers/qwen3_tokenizer.json")
   *
   * # Example
   * ```typescript
   * const tokenizer = Qwen3Tokenizer.fromPretrained();
   * const tokens = tokenizer.encode("Hello, world!");
   * ```
   */
  static fromPretrained(tokenizerPath: string): Promise<Qwen3Tokenizer>;
  /**
   * Encode text to token IDs
   *
   * # Arguments
   * * `text` - Text to encode
   * * `add_special_tokens` - Whether to add special tokens (default: true)
   *
   * # Returns
   * Array of token IDs as Int32Array
   *
   * # Example
   * ```typescript
   * const tokens = tokenizer.encode("Hello, world!");
   * console.log(tokens); // Int32Array [9906, 11, 1879, 0]
   * ```
   */
  encode(text: string, addSpecialTokens?: boolean | undefined | null): Promise<Uint32Array>;
  /**
   * Encode multiple texts in batch
   *
   * # Arguments
   * * `texts` - Array of texts to encode
   * * `add_special_tokens` - Whether to add special tokens (default: true)
   *
   * # Returns
   * Array of Int32Arrays, one for each text
   */
  encodeBatch(texts: Array<string>, addSpecialTokens?: boolean | undefined | null): Promise<Array<Uint32Array>>;
  /**
   * Decode token IDs to text
   *
   * # Arguments
   * * `token_ids` - Token IDs to decode
   * * `skip_special_tokens` - Whether to skip special tokens (default: true)
   *
   * # Returns
   * Decoded text string
   *
   * # Example
   * ```typescript
   * const text = tokenizer.decode(new Int32Array([9906, 11, 1879, 0]));
   * console.log(text); // "Hello, world!"
   * ```
   */
  decode(tokenIds: Uint32Array, skipSpecialTokens?: boolean | undefined | null): Promise<string>;
  /**
   * Decode multiple token sequences in batch
   *
   * # Arguments
   * * `token_ids_batch` - Array of token ID arrays to decode
   * * `skip_special_tokens` - Whether to skip special tokens (default: true)
   *
   * # Returns
   * Array of decoded text strings
   */
  decodeBatch(
    tokenIdsBatch: Array<Uint32Array>,
    skipSpecialTokens?: boolean | undefined | null,
  ): Promise<Array<string>>;
  /**
   * Apply chat template to messages and encode
   *
   * Supports both simple ChatML format and full Jinja2 template rendering with tools.
   * When tools are provided or a chat template exists, uses Jinja2 rendering.
   * Otherwise falls back to simple ChatML format.
   *
   * # Arguments
   * * `messages` - Array of chat messages
   * * `add_generation_prompt` - Whether to add assistant prompt at end (default: true)
   * * `tools` - Optional array of tool definitions for function calling
   * * `enable_thinking` - Optional flag to enable thinking mode (<think> tags)
   *
   * # Returns
   * Encoded token IDs ready for model input
   *
   * # Example
   * ```typescript
   * const messages = [
   *   { role: "system", content: "You are a helpful assistant." },
   *   { role: "user", content: "What is 2+2?" }
   * ];
   * const tokens = tokenizer.applyChatTemplate(messages, true);
   *
   * // With tools
   * const tools = [{
   *   type: "function",
   *   function: { name: "get_weather", description: "Get weather info" }
   * }];
   * const tokens = tokenizer.applyChatTemplate(messages, true, tools);
   * ```
   */
  applyChatTemplate(
    messages: Array<ChatMessage>,
    addGenerationPrompt?: boolean | undefined | null,
    tools?: Array<ToolDefinition> | undefined | null,
    enableThinking?: boolean | undefined | null,
  ): Promise<Uint32Array>;
  /** Get vocabulary size */
  vocabSize(): number;
  /** Get PAD token ID */
  getPadTokenId(): number;
  /** Get EOS token ID */
  getEosTokenId(): number;
  /** Get BOS token ID (if exists) */
  getBosTokenId(): number | null;
  /** Convert token ID to string */
  idToToken(id: number): string | null;
  /** Convert token string to ID */
  tokenToId(token: string): number | null;
  /** Get the special token for IM_START */
  getImStartToken(): string;
  /** Get the special token for IM_END */
  getImEndToken(): string;
  /** Get the special token for ENDOFTEXT (used as PAD) */
  getEndoftextToken(): string;
}

/**
 * A tensor that tracks gradients for automatic differentiation
 *
 * This is a wrapper around MxArray that provides:
 * - Gradient tracking
 * - Automatic gradient accumulation
 * - Integration with manual backward passes
 */
export declare class Tensor {
  /** Create a tensor from float32 data */
  static fromFloat32(data: Float32Array, shape: BigInt64Array, requiresGrad?: boolean | undefined | null): Tensor;
  /** Create a tensor from int32 data */
  static fromInt32(data: Int32Array, shape: BigInt64Array, requiresGrad?: boolean | undefined | null): Tensor;
  /** Get the shape of the underlying data */
  dataShape(): BigInt64Array;
  /** Get the shape of the gradient (if it exists) */
  gradShape(): BigInt64Array | null;
  /** Check if gradient exists */
  hasGrad(): boolean;
  /** Check if this tensor requires gradients */
  get requiresGrad(): boolean;
  /** Set whether this tensor requires gradients */
  set requiresGrad(requiresGrad: boolean);
  /** Zero out the gradient */
  zeroGrad(): void;
  /**
   * Accumulate gradient
   *
   * If gradient already exists, add to it. Otherwise, set it.
   * Note: This takes ownership of the gradient array.
   */
  accumulateGrad(grad: MxArray): void;
  /** Get the shape of the tensor */
  shape(): BigInt64Array;
  /** Convert data to Float32 array */
  toFloat32(): Float32Array;
  /** Convert gradient to Float32 array (if it exists) */
  gradToFloat32(): Float32Array | null;
  /** Convert to Int32 array */
  toInt32(): Int32Array;
  /**
   * Detach this tensor from the computation graph
   *
   * Returns a new tensor with the same data but no gradient tracking
   */
  detach(): Tensor;
  /** Create a tensor of zeros */
  static zeros(
    shape: BigInt64Array,
    dtype?: DType | undefined | null,
    requiresGrad?: boolean | undefined | null,
  ): Tensor;
  /** Create a tensor of ones */
  static ones(
    shape: BigInt64Array,
    dtype?: DType | undefined | null,
    requiresGrad?: boolean | undefined | null,
  ): Tensor;
  /** Evaluate the underlying array */
  eval(): void;
}

/**
 * PP-OCRv5 Text Detection model (DBNet with PPHGNetV2 backbone).
 *
 * Detects text lines in document images and returns bounding boxes.
 */
export declare class TextDetModel {
  /**
   * Load a TextDetModel from a directory containing model.safetensors.
   *
   * # Arguments
   * * `model_path` - Path to model directory
   */
  static load(modelPath: string): TextDetModel;
  /**
   * Detect text lines in an image.
   *
   * # Arguments
   * * `image_data` - Encoded image bytes (PNG/JPEG)
   * * `threshold` - Optional detection threshold (default from config, typically 0.3)
   *
   * # Returns
   * * Vec of TextBox with bounding boxes and confidence scores
   */
  detect(imageData: Buffer, threshold?: number | undefined | null): Array<TextBox>;
  /**
   * Detect text lines from raw RGB pixel data.
   *
   * # Arguments
   * * `rgb_data` - Raw RGB pixel data
   * * `width` - Image width
   * * `height` - Image height
   * * `threshold` - Optional detection threshold (default from config)
   *
   * # Returns
   * * Vec of TextBox with bounding boxes and confidence scores
   */
  detectCrop(rgbData: Uint8Array, width: number, height: number, threshold?: number | undefined | null): Array<TextBox>;
}

/**
 * PP-OCRv5 Text Recognition model (PPHGNetV2 + SVTR + CTC).
 *
 * Recognizes text from cropped text line images.
 */
export declare class TextRecModel {
  /**
   * Load a TextRecModel from a directory containing model.safetensors.
   *
   * # Arguments
   * * `model_path` - Path to model directory
   * * `dict_path` - Path to character dictionary text file
   */
  static load(modelPath: string, dictPath: string): TextRecModel;
  /**
   * Recognize text from encoded image bytes.
   *
   * # Arguments
   * * `image_data` - Encoded image bytes (PNG/JPEG)
   *
   * # Returns
   * * RecResult with recognized text and confidence score
   */
  recognize(imageData: Buffer): RecResult;
  /**
   * Recognize text from multiple encoded images.
   *
   * # Arguments
   * * `images` - Vec of encoded image bytes (PNG/JPEG)
   *
   * # Returns
   * * Vec of RecResult with recognized text and confidence scores
   */
  recognizeBatch(images: Array<Buffer>): Array<RecResult>;
  /**
   * Recognize text from raw RGB crop data.
   *
   * # Arguments
   * * `rgb_data` - Raw RGB pixel data of a cropped text line
   * * `width` - Image width
   * * `height` - Image height
   *
   * # Returns
   * * RecResult with recognized text and confidence score
   */
  recognizeCrop(rgbData: Uint8Array, width: number, height: number): RecResult;
}

/** Result from VLM chat */
export declare class VlmChatResult {
  /** Get the response text */
  get text(): string;
  /** Get the generated tokens */
  get tokens(): MxArray;
  /** Get the log probabilities */
  get logprobs(): MxArray;
  /** Get the finish reason */
  get finishReason(): 'stop' | 'length' | 'repetition';
  /** Get the number of tokens generated */
  get numTokens(): number;
}
export type VLMChatResult = VlmChatResult;

/**
 * Vision-Language Model
 *
 * A generic VLM for OCR and document understanding tasks.
 * Currently supports PaddleOCR-VL architecture (vision encoder + ERNIE language model).
 */
export declare class VLModel {
  /** Create a new PaddleOCR-VL model */
  constructor(config: ModelConfig);
  /** Set the tokenizer */
  setTokenizer(tokenizer: Qwen3Tokenizer): void;
  /** Check if tokenizer is available */
  get hasTokenizer(): boolean;
  /**
   * Chat with the VLM model
   *
   * High-level API for conversational interaction with images.
   *
   * # Arguments
   * * `messages` - Chat messages (role + content)
   * * `config` - Chat configuration (including images for automatic processing)
   *
   * # Returns
   * * VLMChatResult with generated text
   *
   * # Example
   * ```typescript
   * const result = await model.chat(
   *   [{ role: 'user', content: 'Describe this image.' }],
   *   { images: [readFileSync('./photo.jpg')], maxNewTokens: 256 }
   * );
   * ```
   */
  chat(messages: Array<VlmChatMessage>, config?: VlmChatConfig | undefined | null): Promise<VlmChatResult>;
  /**
   * Simple OCR: extract text from encoded image bytes
   *
   * Convenience method that processes an image and extracts all text.
   *
   * # Arguments
   * * `image_data` - Encoded image bytes (PNG/JPEG)
   * * `prompt` - Optional custom prompt (default: "Extract all text from this image.")
   *
   * # Returns
   * * Extracted text as a string
   *
   * # Example
   * ```typescript
   * const text = await model.ocr(imageBuffer);
   * console.log(text);
   * ```
   */
  ocr(imageData: Buffer, prompt?: string | undefined | null): Promise<string>;
  /**
   * Get input embeddings with vision features merged
   *
   * # Arguments
   * * `input_ids` - Token IDs [batch, seq_len]
   * * `pixel_values` - Optional image patches [batch, seq, channels, patch_h, patch_w]
   * * `image_grid_thw` - Optional grid dimensions [num_images, 3]
   *
   * # Returns
   * * Input embeddings with vision features inserted at image token positions
   */
  getInputEmbeddings(
    inputIds: MxArray,
    pixelValues?: MxArray | undefined | null,
    imageGridThw?: MxArray | undefined | null,
  ): MxArray;
  /**
   * Forward pass
   *
   * # Arguments
   * * `input_ids` - Token IDs [batch, seq_len]
   * * `pixel_values` - Optional image patches
   * * `image_grid_thw` - Optional grid dimensions
   * * `mask` - Optional attention mask
   *
   * # Returns
   * * Logits [batch, seq_len, vocab_size]
   */
  forward(
    inputIds: MxArray,
    pixelValues?: MxArray | undefined | null,
    imageGridThw?: MxArray | undefined | null,
    mask?: MxArray | undefined | null,
  ): MxArray;
  /**
   * Generate text tokens given input tokens and optional image
   *
   * Uses KV caching for efficient generation - each step only processes the
   * new token(s) while reusing cached key-value states from previous tokens.
   * Vision features are computed once at the start and cached.
   *
   * # Arguments
   * * `input_ids` - Input token IDs [1, seq_len]
   * * `pixel_values` - Optional image patches [1, num_patches, C, H, W]
   * * `image_grid_thw` - Optional grid dimensions [1, 3]
   * * `config` - Generation configuration
   *
   * # Returns
   * * GenerationResult with tokens, logprobs, and finish reason
   */
  generate(
    inputIds: MxArray,
    pixelValues?: MxArray | undefined | null,
    imageGridThw?: MxArray | undefined | null,
    config?: GenerationConfig | undefined | null,
  ): Promise<GenerationResult>;
  /**
   * Batch OCR: extract text from multiple images simultaneously
   *
   * Processes N images with sequential prefill + batched decode for ~N× decode throughput.
   *
   * # Arguments
   * * `images` - Encoded image buffers
   * * `config` - Optional chat configuration (shared across all items)
   *
   * # Returns
   * * Vec of extracted text strings, one per image
   *
   * # Example
   * ```typescript
   * import { readFileSync } from 'fs';
   * const images = ['page1.jpg', 'page2.jpg'].map(p => readFileSync(p));
   * const texts = await model.ocrBatch(images);
   * ```
   */
  ocrBatch(images: Array<Buffer>, config?: VlmChatConfig | undefined | null): Promise<Array<string>>;
  /**
   * Batch chat: process multiple items simultaneously
   *
   * Sequential prefill + batched decode. Each item can have different images/prompts.
   *
   * # Arguments
   * * `batch` - Batch items, each with messages and optional images
   * * `config` - Optional shared chat configuration
   *
   * # Returns
   * * Vec of VLMChatResult, one per batch item
   */
  batch(batch: Array<VlmBatchItem>, config?: VlmChatConfig | undefined | null): Promise<Array<VlmChatResult>>;
  /** Get model configuration */
  get config(): ModelConfig;
  /** Check if model is fully initialized */
  get isInitialized(): boolean;
  /**
   * Load a VLM from disk
   *
   * Loads a model from a directory containing:
   * - config.json: Model configuration
   * - model.safetensors or model-*.safetensors: Model weights in SafeTensors format
   *
   * # Arguments
   * * `model_path` - Path to the model directory
   *
   * # Returns
   * * A fully initialized VLModel with loaded weights
   *
   * # Example
   * ```typescript
   * import { VLModel } from '@mlx-node/vlm';
   * const model = await VLModel.load('./models/paddleocr-vl');
   * const result = await model.chat(messages, { images: [readFileSync('./image.jpg')] });
   * ```
   */
  static load(modelPath: string): Promise<VLModel>;
  /**
   * Load model configuration from disk without loading weights
   *
   * This is useful for inspecting model configuration before loading the full model.
   *
   * # Arguments
   * * `model_path` - Path to the model directory containing config.json
   *
   * # Returns
   * * ModelConfig with vision and text configuration
   *
   * # Example
   * ```typescript
   * import { VLModel } from '@mlx-node/vlm';
   * const config = await VLModel.loadConfig('./models/paddleocr-vl');
   * console.log(config.visionConfig.hiddenSize);
   * ```
   */
  static loadConfig(modelPath: string): Promise<ModelConfig>;
}

/**
 * Build RewardOutput array from generation results.
 *
 * Parses tool calls and thinking from completions, creating structured outputs
 * aligned with the ChatResult structure.
 */
export declare function buildRewardOutputs(
  prompts: Array<string>,
  completions: Array<string>,
  tokenCounts: Array<number>,
  finishReasons: Array<string>,
  groupSize: number,
): Array<RewardOutput>;

/** Unified chat configuration shared by all model variants (Qwen3, Qwen3.5, Qwen3.5 MoE). */
export interface ChatConfig {
  maxNewTokens?: number | undefined;
  temperature?: number | undefined;
  topK?: number | undefined;
  topP?: number | undefined;
  minP?: number | undefined;
  /** Repetition penalty (1.0 = disabled). Penalizes tokens already in context. */
  repetitionPenalty?: number | undefined;
  /** Size of the context window for repetition penalty (default: 256) */
  repetitionContextSize?: number | undefined;
  /**
   * Presence penalty (0.0 = disabled). Subtracts a flat penalty from logits of any
   * token that appeared at least once in context. Matches OpenAI API semantics.
   */
  presencePenalty?: number | undefined;
  /** Number of recent tokens to consider for presence penalty (default: 20) */
  presenceContextSize?: number | undefined;
  /**
   * Frequency penalty (0.0 = disabled). Subtracts penalty * occurrence_count from
   * logits of each token in context. Matches OpenAI API semantics.
   */
  frequencyPenalty?: number | undefined;
  /** Number of recent tokens to consider for frequency penalty (default: 20) */
  frequencyContextSize?: number | undefined;
  /** Max consecutive identical tokens before stopping (default: 16, 0 = disabled) */
  maxConsecutiveTokens?: number | undefined;
  /** Max n-gram repetitions before stopping (default: 3, 0 = disabled) */
  maxNgramRepeats?: number | undefined;
  /** Max pattern size for n-gram repetition detection (default: 64) */
  ngramSize?: number | undefined;
  tools?: Array<ToolDefinition>;
  /**
   * Enable thinking mode (Qwen3's <think> tags). Default: true (model thinks naturally).
   * Set to false to suppress thinking by injecting empty <think></think> tags.
   */
  enableThinking?: boolean | undefined;
  /**
   * Parse and execute complete tool-call blocks that appear inside reasoning.
   * Default: false.
   */
  allowToolCallsInReasoning?: boolean | undefined;
  /** When true, include performance metrics (TTFT, prefill tok/s, decode tok/s) in the result */
  reportPerformance?: boolean | undefined;
  /**
   * Reuse KV cache across chat() calls for incremental prefill. Default: true.
   * When true, the model preserves its KV cache after generation. On the next
   * chat() call, it prefix-matches the new token sequence against the cached
   * tokens and only prefills the delta — avoiding redundant computation for
   * multi-turn conversations.
   */
  reuseCache?: boolean | undefined;
}

/** Chat message with tool calling support */
export interface ChatMessage {
  /** Role: "system", "user", "assistant", or "tool" */
  role: 'system' | 'user' | 'assistant' | 'tool' | (string & {});
  /** Message content */
  content: string;
  /** Tool calls made by the assistant (for assistant messages) */
  toolCalls?: Array<ToolCall>;
  /** Tool call ID this message is responding to (for tool messages) */
  toolCallId?: string;
  /** Reasoning content for thinking mode (used with <think> tags) */
  reasoningContent?: string;
  /** Image data for VLM models (encoded image bytes: PNG/JPEG, passed as Uint8Array/Buffer) */
  images?: Array<Uint8Array> | undefined;
}

/** Unified chat result shared by all model variants (Qwen3, Qwen3.5, Qwen3.5 MoE). */
export interface ChatResult {
  text: string;
  toolCalls: Array<ToolCallResult>;
  thinking?: string;
  numTokens: number;
  finishReason: string;
  rawText: string;
  /** Performance metrics (present when `reportPerformance: true` in config) */
  performance?: PerformanceMetrics;
}

/** Chat message role (lowercase values matching standard convention) */
export declare const enum ChatRole {
  /** User message */
  User = 'User',
  /** Assistant response */
  Assistant = 'Assistant',
  /** System prompt */
  System = 'System',
  /** Tool response */
  Tool = 'Tool',
}

/** A single chunk emitted during streaming chat generation. */
export interface ChatStreamChunk {
  text: string;
  done: boolean;
  finishReason?: string;
  toolCalls?: Array<ToolCallResult>;
  thinking?: string;
  numTokens?: number;
  rawText?: string;
  /** Performance metrics (only present in the final chunk when `reportPerformance: true`) */
  performance?: PerformanceMetrics;
}

/** Result from classify_and_rotate: orientation info + corrected image bytes. */
export interface ClassifyRotateResult {
  /** Detected rotation angle (0, 90, 180, or 270 degrees) */
  angle: number;
  /** Confidence score */
  score: number;
  /** Angle label as string */
  label: string;
  /** Corrected image as PNG bytes (or original bytes if angle=0) */
  image: Uint8Array;
}

/**
 * Structured completion information aligned with ChatResult.
 * Contains pre-parsed tool calls, thinking, and clean text.
 */
export interface CompletionInfo {
  /** Clean text with <tool_call> and <think> tags removed */
  text: string;
  /** Raw output before tag stripping (for debugging/XML parsing) */
  rawText: string;
  /** Parsed tool calls (arguments are already JS objects) */
  toolCalls: Array<ToolCallResult>;
  /** Extracted thinking/reasoning from <think> tags (null if none) */
  thinking?: string;
  /** Number of tokens generated */
  numTokens: number;
  /** Finish reason: "stop" | "length" | "tool_calls" */
  finishReason: string;
}

export interface ConversionOptions {
  /** Input directory containing model files (config.json, model.safetensors) */
  inputDir: string;
  /** Output directory for converted model */
  outputDir: string;
  /** Target dtype for conversion (default: "float32") */
  dtype?: string;
  /** Whether to verbose logging (default: false) */
  verbose?: boolean;
  /** Model type for model-specific weight sanitization (e.g., "paddleocr-vl") */
  modelType?: string;
  /** Enable quantization of converted weights */
  quantize?: boolean;
  /** Quantization bits: 4 (default) or 8 */
  quantBits?: number;
  /** Quantization group size (default: 64 for affine, 32 for mxfp8) */
  quantGroupSize?: number;
  /** Quantization mode: "affine" (default) or "mxfp8" */
  quantMode?: string;
  /**
   * Quantization recipe for per-layer mixed-bit quantization.
   * Options: mixed_2_6, mixed_3_4, mixed_3_6, mixed_4_6, qwen3_5
   */
  quantRecipe?: string;
  /**
   * Path to an imatrix GGUF file for AWQ-style pre-scaling.
   * Improves quantization quality by amplifying important weight channels.
   */
  imatrixPath?: string;
}

export interface ConversionResult {
  /** Number of tensors converted */
  numTensors: number;
  /** Total number of parameters */
  numParameters: number;
  /** Output model path */
  outputPath: string;
  /** List of converted tensor names */
  tensorNames: Array<string>;
}

export declare function convertForeignWeights(options: ForeignConversionOptions): ForeignConversionResult;

/**
 * Convert a HuggingFace SafeTensors model to MLX format
 *
 * This function:
 * 1. Loads SafeTensors model from input directory
 * 2. Converts all tensors to specified dtype (default: float32)
 * 3. Saves converted model to output directory
 * 4. Copies config.json and tokenizer files
 *
 * # Arguments
 * * `options` - Conversion options (input_dir, output_dir, dtype, verbose)
 *
 * # Returns
 * * ConversionResult with statistics about the conversion
 *
 * # Example
 * ```typescript
 * import { convertModel } from '../../index.cjs';
 *
 * const result = await convertModel({
 *   inputDir: '.cache/models/qwen3-0.6b',
 *   outputDir: '.cache/models/qwen3-0.6b-mlx',
 *   dtype: 'float32',
 *   verbose: true
 * });
 *
 * console.log(`Converted ${result.numTensors} tensors (${result.numParameters} parameters)`);
 * ```
 */
export declare function convertModel(options: ConversionOptions): Promise<ConversionResult>;

/** Create a default PaddleOCR-VL 1.5 configuration (JS factory function) */
export declare function createPaddleocrVlConfig(): ModelConfig;

/** Create a default Qianfan-OCR configuration (JS factory function) */
export declare function createQianfanOcrConfig(): QianfanOcrConfig;

/** Document element - either a table or paragraph */
export interface DocumentElement {
  elementType: ElementType;
  /** Table data (only present if element_type is Table) */
  table?: Table;
  /** Paragraph data (only present if element_type is Paragraph) */
  paragraph?: Paragraph;
}

export declare const enum DType {
  Float32 = 0,
  Int32 = 1,
  Float16 = 2,
  BFloat16 = 3,
  Uint32 = 4,
  Uint8 = 5,
}

/** Document element type */
export declare const enum ElementType {
  Table = 'Table',
  Paragraph = 'Paragraph',
}

export interface ForeignConversionOptions {
  /** Path to the input weights file (.pdparams, .pkl, .pt, .pth) */
  inputPath: string;
  /** Output directory for model.safetensors + config.json */
  outputDir: string;
  /** Model type: "pp-lcnet-ori" or "uvdoc" */
  modelType: string;
  /** Enable verbose logging */
  verbose?: boolean;
}

export interface ForeignConversionResult {
  numTensors: number;
  outputPath: string;
  tensorNames: Array<string>;
}

/** Format parsed document according to config */
export declare function formatDocument(doc: ParsedDocument, config?: ParserConfig | undefined | null): string;

/** Function definition for tool calling */
export interface FunctionDefinition {
  /** Name of the function */
  name: string;
  /** Description of what the function does */
  description?: string;
  /** Parameter schema */
  parameters?: FunctionParameters;
}

/** Function parameters schema (JSON Schema subset) */
export interface FunctionParameters {
  /** Type (usually "object") */
  type: string;
  /** JSON string of property definitions */
  properties?: string;
  /** List of required parameter names */
  required?: Array<string>;
}

/** Configuration for text generation */
export interface GenerationConfig {
  /** Maximum number of new tokens to generate (default: 2048) */
  maxNewTokens?: number;
  /** Sampling temperature (0 = greedy, higher = more random) (default: 1.0) */
  temperature?: number;
  /** Top-k sampling: keep only top k tokens (0 = disabled) (default: 0) */
  topK?: number;
  /** Top-p (nucleus) sampling: keep tokens with cumulative prob < p (default: 1.0) */
  topP?: number;
  /** Min-p sampling: keep tokens with prob > min_p * max_prob (default: 0.0) */
  minP?: number;
  /** Repetition penalty factor (1.0 = no penalty, 1.1-1.5 typical) (default: 1.0) */
  repetitionPenalty?: number;
  /**
   * Number of recent tokens to consider for repetition penalty (default: 20)
   * Matches mlx-lm default. Larger values catch longer patterns but use more memory
   */
  repetitionContextSize?: number;
  /**
   * Presence penalty (0.0 = disabled). Subtracts a flat penalty from logits of any
   * token that appeared at least once in context. Matches OpenAI API semantics.
   */
  presencePenalty?: number;
  /** Number of recent tokens to consider for presence penalty (default: 20) */
  presenceContextSize?: number;
  /**
   * Frequency penalty (0.0 = disabled). Subtracts penalty * occurrence_count from
   * logits of each token in context. Matches OpenAI API semantics.
   */
  frequencyPenalty?: number;
  /** Number of recent tokens to consider for frequency penalty (default: 20) */
  frequencyContextSize?: number;
  /**
   * Stop if same token repeats this many times consecutively (default: 16)
   * Set to 0 to disable. Prevents OOM from degenerate repetitive generation.
   */
  maxConsecutiveTokens?: number;
  /**
   * Stop if a pattern repeats this many times consecutively (default: 3)
   * Set to 0 to disable. Detects patterns like "A B A B A B".
   * Uses range-based detection: checks all pattern sizes from 2 to ngram_size.
   */
  maxNgramRepeats?: number;
  /**
   * Maximum pattern size for repetition detection (default: 64)
   * All pattern sizes from 2 up to this value are checked each decode step.
   * Larger values catch long phrase-level repetition common in small models.
   */
  ngramSize?: number;
  /** EOS token ID (generation stops when this is generated) */
  eosTokenId?: number;
  /** Whether to return log probabilities (always true for GRPO) */
  returnLogprobs?: boolean;
  /**
   * Prefill step size for chunked processing of long prompts (default: 2048)
   * When the prompt length exceeds this value, it will be processed in chunks
   * to improve memory efficiency and enable async pipelining.
   * Set to 0 to disable chunking and process the entire prompt at once.
   */
  prefillStepSize?: number;
  /**
   * KV cache quantization bits (default: 16 = no quantization)
   * - 16: Full precision (bfloat16/float16), no quantization
   * - 8: 8-bit quantization, ~2x memory savings, minimal quality loss
   * - 4: 4-bit quantization, ~4x memory savings, some quality degradation
   *
   * Quantized KV cache is useful for long sequences where memory becomes a bottleneck.
   * Note: Adds dequantization overhead per forward pass.
   */
  kvCacheBits?: number;
  /**
   * KV cache quantization group size (default: 64)
   * Number of elements per quantization group. Smaller groups = better accuracy
   * but more overhead from storing scales/biases.
   * Only used when kv_cache_bits is 4 or 8.
   */
  kvCacheGroupSize?: number;
  /**
   * Number of draft tokens to generate speculatively (default: 5)
   * Only used when a draft model is provided for speculative decoding.
   * Higher values can increase throughput but may reduce acceptance rate.
   */
  numDraftTokens?: number;
}

/** Get expected weight keys for PaddleOCR-VL model */
export declare function getExpectedWeightKeys(): Array<string>;

export interface GgufConversionOptions {
  /** Path to the GGUF file */
  inputPath: string;
  /** Output directory for converted SafeTensors model */
  outputDir: string;
  /** Target dtype: "float32", "float16", "bfloat16" (default: keep original) */
  dtype?: string;
  /** Enable verbose logging */
  verbose?: boolean;
  /** Enable quantization of converted weights */
  quantize?: boolean;
  /** Quantization bits (default: 4) */
  quantBits?: number;
  /** Quantization group size (default: 64) */
  quantGroupSize?: number;
  /** Quantization mode: "affine" or "mxfp8" */
  quantMode?: string;
  /**
   * Quantization recipe for per-layer mixed-bit quantization.
   * Options: mixed_2_6, mixed_3_4, mixed_3_6, mixed_4_6, qwen3_5, unsloth
   */
  quantRecipe?: string;
  /**
   * Path to an imatrix GGUF file for AWQ-style pre-scaling.
   * Improves quantization quality by amplifying important weight channels.
   */
  imatrixPath?: string;
  /**
   * Output filename (default: "model.safetensors").
   * Useful for saving vision weights separately (e.g., "vision.safetensors").
   */
  outputFilename?: string;
  /**
   * When true, remap LLM weight keys for VLM compatibility:
   * "model.X" → "language_model.model.X", "lm_head.X" → "language_model.lm_head.X"
   * This makes the safetensors compatible with mlx-vlm.
   */
  vlmKeyPrefix?: boolean;
}

export interface GgufConversionResult {
  numTensors: number;
  numParameters: number;
  outputPath: string;
  tensorNames: Array<string>;
  sourceFormat: string;
}

/** InternViT vision encoder configuration */
export interface InternVisionConfig {
  hiddenSize: number;
  intermediateSize: number;
  numHiddenLayers: number;
  numAttentionHeads: number;
  numChannels: number;
  imageSize: number;
  patchSize: number;
  layerNormEps: number;
  qkvBias: boolean;
  /** Drop path rate (inference only, always 0) */
  dropPathRate: number;
}

/** A single detected layout element. */
export interface LayoutElement {
  /** Detection confidence score */
  score: number;
  /** Class label ID (0-24) */
  label: number;
  /** Human-readable label name (e.g., "title", "text", "table") */
  labelName: string;
  /** Bounding box in original image coordinates [x1, y1, x2, y2] */
  bbox: Array<number>;
  /** Reading order index (0 = first element to read) */
  order: number;
}

/** Full model configuration */
export interface ModelConfig {
  visionConfig: VisionConfig;
  textConfig: TextConfig;
  modelType: string;
  ignoreIndex: number;
  imageTokenId: number;
  videoTokenId: number;
  visionStartTokenId: number;
  visionEndTokenId: number;
  eosTokenId: number;
}

/** Result from document orientation classification. */
export interface OrientationResult {
  /** Detected rotation angle (0, 90, 180, or 270 degrees) */
  angle: number;
  /** Confidence score */
  score: number;
  /** Angle label as string */
  label: string;
}

/** Output format options */
export declare const enum OutputFormat {
  /** Raw output with minimal processing */
  Raw = 'Raw',
  /** Plain text with aligned columns */
  Plain = 'Plain',
  /** Markdown tables */
  Markdown = 'Markdown',
  /** HTML tables */
  Html = 'Html',
  /** JSON structured output */
  Json = 'Json',
}

/** Paged attention memory statistics (NAPI-compatible) */
export interface PagedCacheStats {
  /** Total number of blocks in the pool */
  totalBlocks: number;
  /** Number of free blocks */
  freeBlocks: number;
  /** Number of allocated blocks */
  allocatedBlocks: number;
  /** Total memory in MB */
  totalMemoryMb: number;
  /** Used memory in MB */
  usedMemoryMb: number;
  /** Utilization percentage */
  utilizationPercent: number;
}

/** A completed sequence from paged generation */
export interface PagedCompletedSequence {
  /** Original request ID */
  requestId: string;
  /** All generated tokens (excluding prompt) */
  tokens: Array<number>;
  /** Reason for completion ("stop", "length", "repetition", "tool_calls") */
  finishReason: string;
}

/** Result of a paged generation step */
export interface PagedGenerationStep {
  /** Token outputs for each sequence in the batch */
  outputs: Array<PagedTokenOutput>;
  /** Number of sequences that were in prefill phase */
  numPrefill: number;
  /** Number of sequences that were in decode phase */
  numDecode: number;
}

/** Output from a single token generation step in paged attention */
export interface PagedTokenOutput {
  /** Sequence ID in the scheduler */
  seqId: number;
  /** Request ID for this sequence */
  requestId: string;
  /** Generated token ID */
  token: number;
  /** Log probability of the token (f64 for NAPI compatibility) */
  logprob: number;
  /** Whether this sequence has finished */
  isFinished: boolean;
}

/** A text paragraph */
export interface Paragraph {
  content: string;
}

/** Parsed document structure */
export interface ParsedDocument {
  elements: Array<DocumentElement>;
}

/**
 * Parse and format PaddleOCR-VL response in one step
 *
 * Convenience function that parses the VLM output and formats it
 * according to the specified configuration.
 *
 * # Arguments
 * * `text` - Raw VLM output containing table tokens
 * * `config` - Optional parser configuration (format, trim_cells, etc.)
 *
 * # Returns
 * * Formatted string in the requested format (markdown, plain, html, raw)
 *
 * # Example
 * ```typescript
 * import { parsePaddleResponse } from '@mlx-node/core';
 *
 * // Parse and format as markdown (default)
 * const markdown = parsePaddleResponse(vlmResult.text);
 *
 * // Parse and format as HTML
 * const html = parsePaddleResponse(vlmResult.text, { format: 'html' });
 *
 * // Parse and format as plain text
 * const plain = parsePaddleResponse(vlmResult.text, { format: 'plain' });
 * ```
 */
export declare function parsePaddleResponse(text: string, config?: ParserConfig | undefined | null): string;

/** Parser configuration */
export interface ParserConfig {
  /** Output format (default: 'markdown') */
  format?: OutputFormat;
  /** Whether to trim whitespace from cells (default: true) */
  trimCells?: boolean;
  /** Whether to collapse empty rows (default: true) */
  collapseEmptyRows?: boolean;
}

/** Parse tool calls from text (NAPI export) */
export declare function parseToolCallsFromText(text: string): ParseToolCallsResult;

/** Result of parsing tool calls from text */
export interface ParseToolCallsResult {
  /** Cleaned text with tool_call tags removed */
  text: string;
  /** Parsed tool calls */
  toolCalls: Array<ToolCallResult>;
}

/** Parse VLM output into structured document */
export declare function parseVlmOutput(text: string): ParsedDocument;

export interface PerformanceMetrics {
  ttftMs: number;
  prefillTokensPerSecond: number;
  decodeTokensPerSecond: number;
}

/** Result from a Qianfan-OCR chat() call. */
export interface QianfanChatResult {
  /** Generated text (with thinking/tool_call tags stripped) */
  text: string;
  /** Parsed tool calls (if any) */
  toolCalls: Array<ToolCallResult>;
  /** Thinking content (text inside <think>...</think> tags) */
  thinking?: string;
  /** Number of generated tokens */
  numTokens: number;
  /** Why generation stopped: "stop", "length", or "repetition" */
  finishReason: string;
  /** Raw generated text before parsing */
  rawText: string;
  /** Performance metrics (only present when `reportPerformance: true`) */
  performance?: PerformanceMetrics;
}

/** Full Qianfan-OCR model configuration */
export interface QianfanOcrConfig {
  visionConfig: InternVisionConfig;
  llmConfig: Qwen3LmConfig;
  modelType: string;
  imgContextTokenId: number;
  /** `<img>` token ID */
  imgStartTokenId: number;
  /** `</img>` token ID */
  imgEndTokenId: number;
  /** `<|im_end|>` token ID */
  eosTokenId: number;
  /** Which vision encoder layer to extract features from */
  selectLayer: number;
  /** Pixel shuffle version */
  psVersion: string;
  downsampleRatio: number;
  dynamicImageSize: boolean;
  useThumbnail: boolean;
  maxDynamicPatch: number;
  minDynamicPatch: number;
}

/**
 * Qwen3.5 model configuration (dense variant).
 *
 * For MoE models, use `Qwen3_5MoeConfig` from `qwen3_5_moe`.
 */
export interface Qwen35Config {
  vocabSize: number;
  hiddenSize: number;
  numLayers: number;
  numHeads: number;
  numKvHeads: number;
  intermediateSize: number;
  rmsNormEps: number;
  headDim: number;
  tieWordEmbeddings: boolean;
  attentionBias: boolean;
  maxPositionEmbeddings: number;
  padTokenId: number;
  eosTokenId: number;
  bosTokenId: number;
  linearNumValueHeads: number;
  linearNumKeyHeads: number;
  linearKeyHeadDim: number;
  linearValueHeadDim: number;
  linearConvKernelDim: number;
  fullAttentionInterval: number;
  partialRotaryFactor: number;
  ropeTheta: number;
}

/** Generation configuration for Qwen3.5 */
export interface Qwen35GenerationConfig {
  maxNewTokens: number;
  temperature?: number | undefined;
  topK?: number | undefined;
  topP?: number | undefined;
  minP?: number | undefined;
}

/** Generation result */
export interface Qwen35GenerationResult {
  tokens: Array<number>;
  text: string;
  numTokens: number;
  finishReason: string;
}

/**
 * Qwen3.5 MoE model configuration.
 *
 * Contains all fields including MoE-specific ones (num_experts, etc.).
 */
export interface Qwen35MoeConfig {
  vocabSize: number;
  hiddenSize: number;
  numLayers: number;
  numHeads: number;
  numKvHeads: number;
  intermediateSize: number;
  rmsNormEps: number;
  headDim: number;
  tieWordEmbeddings: boolean;
  attentionBias: boolean;
  maxPositionEmbeddings: number;
  padTokenId: number;
  eosTokenId: number;
  bosTokenId: number;
  linearNumValueHeads: number;
  linearNumKeyHeads: number;
  linearKeyHeadDim: number;
  linearValueHeadDim: number;
  linearConvKernelDim: number;
  fullAttentionInterval: number;
  partialRotaryFactor: number;
  ropeTheta: number;
  numExperts: number;
  numExpertsPerTok: number;
  decoderSparseStep: number;
  sharedExpertIntermediateSize?: number | undefined;
  moeIntermediateSize?: number | undefined;
  normTopkProb: boolean;
  mlpOnlyLayers?: number[] | undefined;
}

/** Generation configuration for Qwen3.5 MoE */
export interface Qwen35MoeGenerationConfig {
  maxNewTokens: number;
  temperature?: number | undefined;
  topK?: number | undefined;
  topP?: number | undefined;
  minP?: number | undefined;
}

/** Generation result */
export interface Qwen35MoeGenerationResult {
  tokens: Array<number>;
  text: string;
  numTokens: number;
  finishReason: string;
}

/** Qwen3 model configuration */
export interface Qwen3Config {
  vocabSize: number;
  hiddenSize: number;
  numLayers: number;
  numHeads: number;
  numKvHeads: number;
  intermediateSize: number;
  rmsNormEps: number;
  ropeTheta: number;
  maxPositionEmbeddings: number;
  headDim: number;
  useQkNorm: boolean;
  tieWordEmbeddings: boolean;
  padTokenId: number;
  eosTokenId: number;
  bosTokenId: number;
  /**
   * Enable paged attention for memory-efficient inference.
   * Default: false (use standard KVCache)
   */
  usePagedAttention?: boolean | undefined;
  /**
   * GPU memory budget for paged KV cache in megabytes.
   * Only used when use_paged_attention is true.
   * Default: 2048 (2GB)
   */
  pagedCacheMemoryMb?: number | undefined;
  /**
   * Block size for paged attention (tokens per block).
   * Only used when use_paged_attention is true.
   * Default: 16
   */
  pagedBlockSize?: number | undefined;
  /**
   * Use FP8 cache for 2x memory reduction (experimental).
   * Only used when use_paged_attention is true.
   * Default: false
   */
  useFp8Cache?: boolean | undefined;
}

/** Qwen3 language model configuration */
export interface Qwen3LmConfig {
  hiddenSize: number;
  numHiddenLayers: number;
  intermediateSize: number;
  numAttentionHeads: number;
  numKeyValueHeads: number;
  headDim: number;
  rmsNormEps: number;
  vocabSize: number;
  maxPositionEmbeddings: number;
  ropeTheta: number;
  useQkNorm: boolean;
  tieWordEmbeddings: boolean;
}

/** Result of text recognition. */
export interface RecResult {
  /** Recognized text */
  text: string;
  /** Confidence score (mean character probability) */
  score: number;
}

/**
 * Reward function input for a single completion.
 * Provides all context needed to compute a reward score.
 */
export interface RewardOutput {
  /** The input prompt text */
  prompt: string;
  /** Structured completion data aligned with ChatResult */
  completion: CompletionInfo;
}

/**
 * Configuration for sampling strategies
 * ⚡ PERFORMANCE: Made Copy to avoid cloning on every token
 */
export interface SamplingConfig {
  /** Temperature for softmax (default: 1.0). Lower = more deterministic */
  temperature?: number;
  /** Number of top tokens to keep (top-k sampling). 0 = disabled */
  topK?: number;
  /** Cumulative probability threshold (top-p/nucleus sampling). 1.0 = disabled */
  topP?: number;
  /** Minimum probability threshold relative to max (min-p sampling). 0 = disabled */
  minP?: number;
}

/** Scheduler statistics (NAPI-compatible) */
export interface SchedulerStatsNapi {
  /** Number of requests waiting to be scheduled */
  numWaiting: number;
  /** Number of sequences currently running */
  numRunning: number;
  /** Number of completed sequences */
  numCompleted: number;
  /** Number of sequences in prefill phase */
  numPrefill: number;
  /** Number of sequences in decode phase */
  numDecode: number;
  /** Total tokens across all running sequences */
  totalRunningTokens: number;
}

/** A table structure */
export interface Table {
  rows: Array<TableRow>;
}

/** A single cell in a table */
export interface TableCell {
  content: string;
  isEmpty: boolean;
}

/** A row in a table */
export interface TableRow {
  cells: Array<TableCell>;
}

/** A detected text bounding box. */
export interface TextBox {
  /** Bounding box in original image coordinates [x1, y1, x2, y2] */
  bbox: Array<number>;
  /** Detection confidence score (mean probability inside box) */
  score: number;
}

/** Language model (text decoder) configuration */
export interface TextConfig {
  modelType: string;
  hiddenSize: number;
  numHiddenLayers: number;
  intermediateSize: number;
  numAttentionHeads: number;
  rmsNormEps: number;
  vocabSize: number;
  numKeyValueHeads: number;
  maxPositionEmbeddings: number;
  ropeTheta: number;
  ropeTraditional: boolean;
  useBias: boolean;
  headDim: number;
  /**
   * Multimodal RoPE sections: [temporal, height, width]
   * These define how the head_dim is split for 3D position encoding
   */
  mropeSection: Array<number>;
}

/** Tool call made by an assistant */
export interface ToolCall {
  /** Optional unique identifier for the tool call */
  id?: string;
  /** Name of the tool/function to call */
  name: string;
  /** JSON string of arguments to pass to the tool */
  arguments: string;
}

/** Structured tool call with parsed arguments */
export interface ToolCallResult {
  /** Unique identifier for this tool call (format: call_<uuid>) */
  id: string;
  /** Name of the tool/function to call */
  name: string;
  /**
   * Parsed arguments as native object (serde_json::Value -> JS object)
   *
   * When status is "ok", this contains the parsed arguments object.
   * When status is "parse_error", this contains the original unparsed string.
   * Otherwise, this is an empty object {}.
   */
  arguments: Record<string, unknown> | string;
  /**
   * Parsing status: "ok" | "invalid_json" | "missing_name" | "parse_error"
   *
   * - "ok": Successfully parsed tool call
   * - "invalid_json": The tool_call tag content was not valid JSON
   * - "missing_name": Valid JSON but no "name" field
   * - "parse_error": Valid JSON but the "arguments" string field couldn't be parsed as JSON
   */
  status: string;
  /** Error message if status != "ok" */
  error?: string;
  /**
   * Raw content from <tool_call> tag (preserved for debugging/persistence)
   * Defaults to empty string for backward compatibility with older JSON
   */
  rawContent: string;
}

/** OpenAI-compatible tool definition */
export interface ToolDefinition {
  /** Tool type (currently only "function" is supported) */
  type: string;
  /** Function definition */
  function: FunctionDefinition;
}

/** Result from document unwarping. */
export interface UnwarpResult {
  /** Unwarped image as PNG bytes */
  image: Buffer;
}

/** Vision encoder configuration */
export interface VisionConfig {
  modelType: string;
  hiddenSize: number;
  intermediateSize: number;
  numHiddenLayers: number;
  numAttentionHeads: number;
  numChannels: number;
  imageSize: number;
  patchSize: number;
  hiddenAct: string;
  layerNormEps: number;
  attentionDropout: number;
  spatialMergeSize: number;
}

/** A batch item for VLM batch inference */
export interface VlmBatchItem {
  /** Chat messages for this item */
  messages: Array<VlmChatMessage>;
  /** Encoded image buffers for this item (one image per item for OCR) */
  images?: Array<Buffer>;
}

/** Configuration for VLM chat */
export interface VlmChatConfig {
  /** Encoded image buffers to process (PNG/JPEG bytes) */
  images?: Array<Buffer>;
  /** Maximum number of new tokens to generate (default: 512) */
  maxNewTokens?: number;
  /** Sampling temperature (0 = greedy, higher = more random) (default: 0.0 for OCR) */
  temperature?: number;
  /** Top-k sampling (default: 0) */
  topK?: number;
  /** Top-p (nucleus) sampling (default: 1.0) */
  topP?: number;
  /** Repetition penalty (default: 1.5) */
  repetitionPenalty?: number;
  /**
   * Presence penalty (0.0 = disabled). Subtracts a flat penalty from logits of any
   * token that appeared at least once in context. Matches OpenAI API semantics.
   */
  presencePenalty?: number;
  /** Number of recent tokens to consider for presence penalty (default: 20) */
  presenceContextSize?: number;
  /**
   * Frequency penalty (0.0 = disabled). Subtracts penalty * occurrence_count from
   * logits of each token in context. Matches OpenAI API semantics.
   */
  frequencyPenalty?: number;
  /** Number of recent tokens to consider for frequency penalty (default: 20) */
  frequencyContextSize?: number;
  /** Whether to return log probabilities (default: false) */
  returnLogprobs?: boolean;
}

/** A chat message with optional image */
export interface VlmChatMessage {
  /** Role of the message sender */
  role: ChatRole;
  /** Text content of the message */
  content: string;
}
