/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path');
const { WASI: __nodeWASI } = require('node:wasi');
const { Worker } = require('node:worker_threads');

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime');

const __rootDir = __nodePath.parse(process.cwd()).root;

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  },
});

const __emnapiContext = __emnapiGetDefaultContext();

const __sharedMemory = new WebAssembly.Memory({
  initial: 16000,
  maximum: 65536,
  shared: true,
});

let __wasmFilePath = __nodePath.join(__dirname, 'mlx-core.wasm32-wasi.wasm');
const __wasmDebugFilePath = __nodePath.join(__dirname, 'mlx-core.wasm32-wasi.debug.wasm');

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath;
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = require.resolve('@mlx-node/core-wasm32-wasi/mlx-core.wasm32-wasi.wasm');
  } catch {
    throw new Error(
      'Cannot find mlx-core.wasm32-wasi.wasm file, and @mlx-node/core-wasm32-wasi package is not installed.',
    );
  }
}

const {
  instance: __napiInstance,
  module: __wasiModule,
  napiModule: __napiModule,
} = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function () {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE);
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv;
    } else {
      return 4;
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    });
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data);
    };

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find((s) => s.toString().includes('kPublicPort'));
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find((s) => s.toString().includes('kHandle'));
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker;
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    };
    return importObject;
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]();
      }
    }
  },
});
module.exports = __napiModule.exports;
module.exports.BatchGenerationResult = __napiModule.exports.BatchGenerationResult;
module.exports.ChatStreamHandle = __napiModule.exports.ChatStreamHandle;
module.exports.DocLayoutModel = __napiModule.exports.DocLayoutModel;
module.exports.PPDocLayoutV3Model = __napiModule.exports.PPDocLayoutV3Model;
module.exports.DocOrientationModel = __napiModule.exports.DocOrientationModel;
module.exports.DocUnwarpModel = __napiModule.exports.DocUnwarpModel;
module.exports.Gemma4Model = __napiModule.exports.Gemma4Model;
module.exports.GenerationResult = __napiModule.exports.GenerationResult;
module.exports.GrpoTrainingEngine = __napiModule.exports.GrpoTrainingEngine;
module.exports.GRPOTrainingEngine = __napiModule.exports.GRPOTrainingEngine;
module.exports.HarrierModel = __napiModule.exports.HarrierModel;
module.exports.Lfm2Model = __napiModule.exports.Lfm2Model;
module.exports.MxArray = __napiModule.exports.MxArray;
module.exports.NativeRewardRegistry = __napiModule.exports.NativeRewardRegistry;
module.exports.OutputStore = __napiModule.exports.OutputStore;
module.exports.PromptCache = __napiModule.exports.PromptCache;
module.exports.QianfanOCRModel = __napiModule.exports.QianfanOCRModel;
module.exports.Qwen35Model = __napiModule.exports.Qwen35Model;
module.exports.Qwen3_5Model = __napiModule.exports.Qwen3_5Model;
module.exports.Qwen35MoeModel = __napiModule.exports.Qwen35MoeModel;
module.exports.Qwen3_5MoeModel = __napiModule.exports.Qwen3_5MoeModel;
module.exports.Qwen3Model = __napiModule.exports.Qwen3Model;
module.exports.Qwen3Tokenizer = __napiModule.exports.Qwen3Tokenizer;
module.exports.ResponseStore = __napiModule.exports.ResponseStore;
module.exports.SftTrainingEngine = __napiModule.exports.SftTrainingEngine;
module.exports.Tensor = __napiModule.exports.Tensor;
module.exports.TextDetModel = __napiModule.exports.TextDetModel;
module.exports.TextRecModel = __napiModule.exports.TextRecModel;
module.exports.VlmChatResult = __napiModule.exports.VlmChatResult;
module.exports.VLMChatResult = __napiModule.exports.VLMChatResult;
module.exports.VLModel = __napiModule.exports.VLModel;
module.exports.buildRewardOutputs = __napiModule.exports.buildRewardOutputs;
module.exports.BuiltinRewardType = __napiModule.exports.BuiltinRewardType;
module.exports.ChatRole = __napiModule.exports.ChatRole;
module.exports.convertForeignWeights = __napiModule.exports.convertForeignWeights;
module.exports.convertGgufToSafetensors = __napiModule.exports.convertGgufToSafetensors;
module.exports.convertModel = __napiModule.exports.convertModel;
module.exports.convertParquetToJsonl = __napiModule.exports.convertParquetToJsonl;
module.exports.createPaddleocrVlConfig = __napiModule.exports.createPaddleocrVlConfig;
module.exports.createQianfanOcrConfig = __napiModule.exports.createQianfanOcrConfig;
module.exports.createRandomQwen35Checkpoint = __napiModule.exports.createRandomQwen35Checkpoint;
module.exports.createRandomQwen35MoeCheckpoint = __napiModule.exports.createRandomQwen35MoeCheckpoint;
module.exports.createRandomQwen3Checkpoint = __napiModule.exports.createRandomQwen3Checkpoint;
module.exports.documentToXlsx = __napiModule.exports.documentToXlsx;
module.exports.DType = __napiModule.exports.DType;
module.exports.ElementType = __napiModule.exports.ElementType;
module.exports.formatDocument = __napiModule.exports.formatDocument;
module.exports.getExpectedWeightKeys = __napiModule.exports.getExpectedWeightKeys;
module.exports.getProfilingData = __napiModule.exports.getProfilingData;
module.exports.isProfilingEnabled = __napiModule.exports.isProfilingEnabled;
module.exports.memoryStats = __napiModule.exports.memoryStats;
module.exports.OutputFormat = __napiModule.exports.OutputFormat;
module.exports.parsePaddleResponse = __napiModule.exports.parsePaddleResponse;
module.exports.parseToolCallsFromText = __napiModule.exports.parseToolCallsFromText;
module.exports.parseVlmOutput = __napiModule.exports.parseVlmOutput;
module.exports.resetProfilingData = __napiModule.exports.resetProfilingData;
module.exports.saveToXlsx = __napiModule.exports.saveToXlsx;
module.exports.setProfilingEnabled = __napiModule.exports.setProfilingEnabled;
module.exports.__internal__ = __napiModule.exports.__internal__;
